patchedDependencies:
  '@capacitor-mlkit/subject-segmentation@8.1.0': patches/@capacitor-mlkit__subject-segmentation@8.1.0.patch
  '@pantrist/capacitor-plugin-ml-kit-text-recognition@8.0.0': patches/@pantrist__capacitor-plugin-ml-kit-text-recognition@8.0.0.patch
