// GENERATED by scripts/gen-seed-demo-scenario.mjs from new_seed/demo-scenario.xlsx — do not edit by hand.
// Edit the workbook, re-run the generator, then db:seed. Spec:
// docs/superpowers/specs/2026-07-29-excel-demo-seed-design.md
const d = (s: string) => new Date(s);

export const demoParts = [
  { id: "00000000-0000-4000-9000-000000000030", brand: "KOA", partNo: "RK73H1JTTD1002F", wclItemNo: "RK73H1JTTD1002F", description: null, defaultCoo: null },
  { id: "00000000-0000-4000-9000-000000000031", brand: "KOA", partNo: "RK73H1JTTD2202F", wclItemNo: "RK73H1JTTD2202F", description: null, defaultCoo: null },
  { id: "00000000-0000-4000-9000-000000000032", brand: "KOA", partNo: "RK73B1JTTD181G", wclItemNo: "RK73B1JTTD181G", description: null, defaultCoo: null },
  { id: "00000000-0000-4000-9000-000000000033", brand: "KOA", partNo: "RK73H2ATTD1372F", wclItemNo: "RK73H2ATTD1372F", description: null, defaultCoo: null },
  { id: "00000000-0000-4000-9000-000000000034", brand: "KOA", partNo: "RK73H1JTTD4702F", wclItemNo: "RK73H1JTTD4702F", description: null, defaultCoo: null }
];

export const demoReceivingOrders = [
  { id: "00000000-0000-4000-9000-000000000001", batchNo: "100001", supplierCode: "KOA", deliveryDate: d("2026-07-28"), orgId: 2, subInventoryCode: "STORE1", status: "pending" },
  { id: "00000000-0000-4000-9000-000000000002", batchNo: "100002", supplierCode: "KOA", deliveryDate: d("2026-07-29"), orgId: 2, subInventoryCode: "STORE1", status: "pending" }
];

export const demoReceivingInvoices = [
  { id: "00000000-0000-4000-9000-000000000003", receivingOrderId: "00000000-0000-4000-9000-000000000001", invoiceNo: "INV-100001-01", supplierCode: "KOA", wclCompanyName: "WCL Components Ltd", totalQty: 5800, totalCtn: 2, deliveryDate: d("2026-07-25"), orgId: 2 },
  { id: "00000000-0000-4000-9000-000000000004", receivingOrderId: "00000000-0000-4000-9000-000000000002", invoiceNo: "INV-100002-01", supplierCode: "KOA", wclCompanyName: "WCL Components Ltd", totalQty: 3400, totalCtn: 2, deliveryDate: d("2026-07-26"), orgId: 2 }
];

export const demoReceivingInvoiceItems = [
  { id: "00000000-0000-4000-9000-000000000005", receivingInvoiceId: "00000000-0000-4000-9000-000000000003", partNo: "RK73H1JTTD1002F", wclItemNo: "RK73H1JTTD1002F", poNo: "PO-KOA-101", poLine: "1", lineQty: 2000, ctnNo: "C1001", dateCode: "2605", lotCode: "L2605A", coo: "JP", cow: "JP", orgId: 2, additionalData: {"boxSize":"26 X 22 X 22","netWeight":1300,"grossWeight":1450,"weightUnit":"g"} },
  { id: "00000000-0000-4000-9000-000000000006", receivingInvoiceId: "00000000-0000-4000-9000-000000000003", partNo: "RK73H1JTTD2202F", wclItemNo: "RK73H1JTTD2202F", poNo: "PO-KOA-101", poLine: "2", lineQty: 1000, ctnNo: "C1001", dateCode: "2605", lotCode: "L2605B", coo: "JP", cow: "JP", orgId: 2, additionalData: null },
  { id: "00000000-0000-4000-9000-000000000007", receivingInvoiceId: "00000000-0000-4000-9000-000000000003", partNo: "RK73B1JTTD181G", wclItemNo: "RK73B1JTTD181G", poNo: "PO-KOA-101", poLine: "3", lineQty: 1500, ctnNo: "C1002", dateCode: "2606", lotCode: "L2606A", coo: "JP", cow: "JP", orgId: 2, additionalData: {"boxSize":"33 X 24 X 18","netWeight":950,"grossWeight":1100,"weightUnit":"g"} },
  { id: "00000000-0000-4000-9000-000000000008", receivingInvoiceId: "00000000-0000-4000-9000-000000000003", partNo: "RK73H2ATTD1372F", wclItemNo: "RK73H2ATTD1372F", poNo: "PO-KOA-101", poLine: "4", lineQty: 800, ctnNo: "C1002", dateCode: "2606", lotCode: "L2606B", coo: "JP", cow: "JP", orgId: 2, additionalData: null },
  { id: "00000000-0000-4000-9000-000000000009", receivingInvoiceId: "00000000-0000-4000-9000-000000000003", partNo: "RK73H1JTTD4702F", wclItemNo: "RK73H1JTTD4702F", poNo: "PO-KOA-101", poLine: "5", lineQty: 500, ctnNo: "C1002", dateCode: "2606", lotCode: "L2606C", coo: "JP", cow: "JP", orgId: 2, additionalData: null },
  { id: "00000000-0000-4000-9000-000000000010", receivingInvoiceId: "00000000-0000-4000-9000-000000000004", partNo: "RK73H1JTTD4702F", wclItemNo: "RK73H1JTTD4702F", poNo: "PO-DAI-201", poLine: "1", lineQty: 1200, ctnNo: "C2001", dateCode: "2607", lotCode: "L2607A", coo: "JP", cow: "JP", orgId: 2, additionalData: {"boxSize":"32 X 22 X 30","netWeight":2100,"grossWeight":2350,"weightUnit":"g"} },
  { id: "00000000-0000-4000-9000-000000000011", receivingInvoiceId: "00000000-0000-4000-9000-000000000004", partNo: "RK73B1JTTD181G", wclItemNo: "RK73B1JTTD181G", poNo: "PO-DAI-201", poLine: "2", lineQty: 600, ctnNo: "C2001", dateCode: "2607", lotCode: "L2607B", coo: "JP", cow: "JP", orgId: 2, additionalData: null },
  { id: "00000000-0000-4000-9000-000000000012", receivingInvoiceId: "00000000-0000-4000-9000-000000000004", partNo: "RK73H2ATTD1372F", wclItemNo: "RK73H2ATTD1372F", poNo: "PO-DAI-201", poLine: "3", lineQty: 900, ctnNo: "C2002", dateCode: "2608", lotCode: "L2608A", coo: "JP", cow: "JP", orgId: 2, additionalData: {"boxSize":"35 X 35 X 22","netWeight":1600,"grossWeight":1800,"weightUnit":"g"} },
  { id: "00000000-0000-4000-9000-000000000013", receivingInvoiceId: "00000000-0000-4000-9000-000000000004", partNo: "RK73H1JTTD1002F", wclItemNo: "RK73H1JTTD1002F", poNo: "PO-DAI-201", poLine: "4", lineQty: 400, ctnNo: "C2002", dateCode: "2608", lotCode: "L2608B", coo: "JP", cow: "JP", orgId: 2, additionalData: null },
  { id: "00000000-0000-4000-9000-000000000014", receivingInvoiceId: "00000000-0000-4000-9000-000000000004", partNo: "RK73H1JTTD2202F", wclItemNo: "RK73H1JTTD2202F", poNo: "PO-DAI-201", poLine: "5", lineQty: 300, ctnNo: "C2002", dateCode: "2608", lotCode: "L2608C", coo: "JP", cow: "JP", orgId: 2, additionalData: null }
];

export const demoPickingOrders = [
  { id: "00000000-0000-4000-9000-000000000015", orderNo: "SO-DEMO-0001", poNo: "CUST-PO-9001", deliveryDate: d("2026-07-30"), shipTo: "ACME Electronics (HK)", customerCode: "ACME", orgId: 2, subInventoryCode: "STORE1", status: "pending" as const },
  { id: "00000000-0000-4000-9000-000000000016", orderNo: "SO-DEMO-0002", poNo: "CUST-PO-9002", deliveryDate: d("2026-08-01"), shipTo: "ACME Electronics (HK)", customerCode: "ACME", orgId: 2, subInventoryCode: "STORE1", status: "pending" as const }
];

export const demoPickingItems = [
  { id: "00000000-0000-4000-9000-000000000017", pickingOrderId: "00000000-0000-4000-9000-000000000015", partNo: "RK73H1JTTD1002F", qty: 1000 },
  { id: "00000000-0000-4000-9000-000000000018", pickingOrderId: "00000000-0000-4000-9000-000000000015", partNo: "RK73H1JTTD2202F", qty: 500 },
  { id: "00000000-0000-4000-9000-000000000019", pickingOrderId: "00000000-0000-4000-9000-000000000016", partNo: "RK73B1JTTD181G", qty: 1000 },
  { id: "00000000-0000-4000-9000-000000000020", pickingOrderId: "00000000-0000-4000-9000-000000000016", partNo: "RK73H1JTTD4702F", qty: 600 },
  { id: "00000000-0000-4000-9000-000000000021", pickingOrderId: "00000000-0000-4000-9000-000000000016", partNo: "RK73H2ATTD1372F", qty: 700 }
];

export const demoShelfBoxes = [
  { id: "BOX-H-20260701-0001", shelfCode: "A-01-01", orgId: 2, subInventoryCode: "STORE1", status: "closed" },
  { id: "BOX-H-20260701-0002", shelfCode: "A-01-02", orgId: 2, subInventoryCode: "STORE1", status: "closed" }
];

export const demoShelfBoxItems = [
  { id: "00000000-0000-4000-9000-000000000022", shelfBoxId: "BOX-H-20260701-0001", partNo: "RK73H1JTTD1002F", qty: 1000 },
  { id: "00000000-0000-4000-9000-000000000023", shelfBoxId: "BOX-H-20260701-0001", partNo: "RK73H1JTTD2202F", qty: 500 },
  { id: "00000000-0000-4000-9000-000000000024", shelfBoxId: "BOX-H-20260701-0002", partNo: "RK73B1JTTD181G", qty: 400 },
  { id: "00000000-0000-4000-9000-000000000025", shelfBoxId: "BOX-H-20260701-0002", partNo: "RK73H1JTTD4702F", qty: 200 }
];

export const demoLots = [
  { id: "00000000-0000-4000-9000-000000000026", partNo: "RK73H1JTTD1002F", dateCode: "2603", lotCode: "L2603A", coo: "JP", cow: "JP", shelfCode: "A-01-01", boxId: "BOX-H-20260701-0001", orgId: 2, subInventoryCode: "STORE1", totalQty: 1000 },
  { id: "00000000-0000-4000-9000-000000000027", partNo: "RK73H1JTTD2202F", dateCode: "2603", lotCode: "L2603B", coo: "JP", cow: "JP", shelfCode: "A-01-01", boxId: "BOX-H-20260701-0001", orgId: 2, subInventoryCode: "STORE1", totalQty: 500 },
  { id: "00000000-0000-4000-9000-000000000028", partNo: "RK73B1JTTD181G", dateCode: "2604", lotCode: "L2604A", coo: "JP", cow: "JP", shelfCode: "A-01-02", boxId: "BOX-H-20260701-0002", orgId: 2, subInventoryCode: "STORE1", totalQty: 400 },
  { id: "00000000-0000-4000-9000-000000000029", partNo: "RK73H1JTTD4702F", dateCode: "2604", lotCode: "L2604B", coo: "JP", cow: "JP", shelfCode: "A-01-02", boxId: "BOX-H-20260701-0002", orgId: 2, subInventoryCode: "STORE1", totalQty: 200 }
];
