// GENERATED by scripts/gen-seed-real-data.mjs — do not edit by hand.
// Source: new_seed/weight/KOA N.W.xls + other.xls (col C unit weight KG → grams per 1 pc).
export const realNetWeights = [
 {
  "partNo": "CCF1N2TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N6.3TTE",
  "weight": 0.19
 },
 {
  "partNo": "CZP1JFTTD301P",
  "weight": 0.035
 },
 {
  "partNo": "CZP2BFTTE800P",
  "weight": 0.04
 },
 {
  "partNo": "CCF1N3.15TTE",
  "weight": 0.2
 },
 {
  "partNo": "CCP2B40DTTE",
  "weight": 0.033
 },
 {
  "partNo": "CCP2B50TTE",
  "weight": 0.03
 },
 {
  "partNo": "CCP2B63TTE",
  "weight": 0.03
 },
 {
  "partNo": "CCP2E100TTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E10HTTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E10TTE",
  "weight": 0.055
 },
 {
  "partNo": "CCP2E15HTTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E20HTTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E20TTE",
  "weight": 0.075
 },
 {
  "partNo": "CCP2E25TTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E35TTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E38HTTE",
  "weight": 0.055
 },
 {
  "partNo": "CCP2E40TTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E45TTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E50HTTE",
  "weight": 0.06
 },
 {
  "partNo": "CCP2E50TTE",
  "weight": 0.075
 },
 {
  "partNo": "RCWCTE",
  "weight": 0.045
 },
 {
  "partNo": "CNZ1J2TTD",
  "weight": 0.028
 },
 {
  "partNo": "CNZ2A4TTE",
  "weight": 0.05
 },
 {
  "partNo": "RK73Z1JTTD",
  "weight": 0.022
 },
 {
  "partNo": "RK73Z2ATTD",
  "weight": 0.028
 },
 {
  "partNo": "SPG20-1308",
  "weight": 26
 },
 {
  "partNo": "J1/4ZCT52A",
  "weight": 0.225
 },
 {
  "partNo": "J1/6ZCMTA",
  "weight": 0.245
 },
 {
  "partNo": "J1/6ZCT52A",
  "weight": 0.155
 },
 {
  "partNo": "JL5CT52A",
  "weight": 0.132
 },
 {
  "partNo": "JL6CT26A",
  "weight": 0.104
 },
 {
  "partNo": "JL6CT52A",
  "weight": 0.166
 },
 {
  "partNo": "TF16SN0.50TTD",
  "weight": 0.022
 },
 {
  "partNo": "NV73A1ETTP8",
  "weight": 0.014
 },
 {
  "partNo": "NV73A2ATTE39",
  "weight": 0.028
 },
 {
  "partNo": "NV73A2ATTE47",
  "weight": 0.028
 },
 {
  "partNo": "NV73A2BTTE39",
  "weight": 0.036
 },
 {
  "partNo": "NV73A2BTTE47",
  "weight": 0.04
 },
 {
  "partNo": "RCSCTE",
  "weight": 0.04
 },
 {
  "partNo": "RCTCTE",
  "weight": 0.035
 },
 {
  "partNo": "RCUCTE",
  "weight": 0.025
 },
 {
  "partNo": "TF10BN0.25TTB",
  "weight": 0.011
 },
 {
  "partNo": "TF10BN0.50TTB",
  "weight": 0.011
 },
 {
  "partNo": "TF16AT0.315TTD",
  "weight": 0.022
 },
 {
  "partNo": "TF16AT0.50TTD",
  "weight": 0.02
 },
 {
  "partNo": "TF16AT1.25TTD",
  "weight": 0.02
 },
 {
  "partNo": "TF16RR0.10TTD",
  "weight": 0.022
 },
 {
  "partNo": "TF16SN0.20TTD",
  "weight": 0.022
 },
 {
  "partNo": "TF16SN0.315TTD",
  "weight": 0.022
 },
 {
  "partNo": "TF16SN0.40TTD",
  "weight": 0.02
 },
 {
  "partNo": "TF16SN0.63TTD",
  "weight": 0.02
 },
 {
  "partNo": "TF16SN1.25TTD",
  "weight": 0.022
 },
 {
  "partNo": "TF16SN2.00TTD",
  "weight": 0.022
 },
 {
  "partNo": "TLRZ1ETTB",
  "weight": 0.01
 },
 {
  "partNo": "TLRZ2ATTD",
  "weight": 0.03
 },
 {
  "partNo": "X7R0603CTTD473K",
  "weight": 0.035
 },
 {
  "partNo": "X7R0805CTTE334K",
  "weight": 0.033
 },
 {
  "partNo": "X7R0805HTTD104K",
  "weight": 0.0375
 },
 {
  "partNo": "Z16CT26A",
  "weight": 0.094
 },
 {
  "partNo": "Z25CT52A",
  "weight": 0.25
 },
 {
  "partNo": "CCF1N0.4TTE",
  "weight": 0.2
 },
 {
  "partNo": "CCF1N1.25TTE",
  "weight": 0.2
 },
 {
  "partNo": "CCF1N1.6TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N10TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N12TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N1TTE",
  "weight": 0.2
 },
 {
  "partNo": "CCF1N2.5TTE",
  "weight": 0.2
 },
 {
  "partNo": "CCF1N4TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N5TTE",
  "weight": 0.19
 },
 {
  "partNo": "CCF1N8TTE",
  "weight": 0.2
 },
 {
  "partNo": "RK73Z1ERTTP",
  "weight": 0.009
 },
 {
  "partNo": "RK73Z1ETTP",
  "weight": 0.01
 },
 {
  "partNo": "RK73Z1HTTC",
  "weight": 0.009
 },
 {
  "partNo": "RK73Z2BTTD",
  "weight": 0.028
 },
 {
  "partNo": "RK73Z2ETTD",
  "weight": 0.032
 },
 {
  "partNo": "RK73Z2HTTE",
  "weight": 0.0475
 },
 {
  "partNo": "RK73Z3ATTE",
  "weight": 0.0575
 },
 {
  "partNo": "RK73ZW2HTTE",
  "weight": 0.0475
 },
 {
  "partNo": "RK73ZW3ATTE",
  "weight": 0.06
 },
 {
  "partNo": "EKMQ451ELL151MM40S(800MA)",
  "weight": 17.52
 },
 {
  "partNo": "BPR58C50LJ",
  "weight": 3.63
 },
 {
  "partNo": "S-1000N20-N4T1U",
  "weight": 0.033
 },
 {
  "partNo": "S-1009N25I-M5T1U",
  "weight": 0.04
 },
 {
  "partNo": "S-1112B33MC-L6STFU",
  "weight": 0.033333
 },
 {
  "partNo": "S-1132B33-M5T1G",
  "weight": 0.03
 },
 {
  "partNo": "S-1135D15-M5T1S",
  "weight": 0.033333
 },
 {
  "partNo": "S-1135D18-M5T1S",
  "weight": 0.03
 },
 {
  "partNo": "S-1135D33-M5T1S",
  "weight": 0.033333
 },
 {
  "partNo": "EMVH350ARA221MJA0G+R",
  "weight": 2.5
 },
 {
  "partNo": "S-1135D33-M5T1U",
  "weight": 0.036
 },
 {
  "partNo": "S-1155B33-U5T1G",
  "weight": 0.15
 },
 {
  "partNo": "S-1170B25UC-OTKTFU",
  "weight": 0.14
 },
 {
  "partNo": "S-1170B33UC-OTSTFU",
  "weight": 0.13
 },
 {
  "partNo": "S-1200B30-M5T1U",
  "weight": 0.04
 },
 {
  "partNo": "S-1206B18-M3T1U",
  "weight": 0.033333
 },
 {
  "partNo": "S-1206B30-M3T1U",
  "weight": 0.03
 },
 {
  "partNo": "S-1206B33-M3T1U",
  "weight": 0.03
 },
 {
  "partNo": "S-1206B50-U3T1U",
  "weight": 0.13
 },
 {
  "partNo": "S-1313A26-N4T1U3",
  "weight": 0.03
 },
 {
  "partNo": "S-1318D30-M5T1U4",
  "weight": 0.033
 },
 {
  "partNo": "S-13R1D36-M5T1U3",
  "weight": 0.033333
 },
 {
  "partNo": "S-1741A21-A6T2U4",
  "weight": 0.02
 },
 {
  "partNo": "S-19680AAAH-K8T2U",
  "weight": 0.0425
 },
 {
  "partNo": "S-19680BAFH-K8T2U",
  "weight": 0.0425
 },
 {
  "partNo": "S-24C02CI-J8T1U",
  "weight": 0.165
 },
 {
  "partNo": "S-24C16CH-T8T2U3",
  "weight": 0.12
 },
 {
  "partNo": "S-35390A-J8T1G",
  "weight": 0.31
 },
 {
  "partNo": "S-35390A-J8T1U",
  "weight": 0.175
 },
 {
  "partNo": "S-5712ACDH1-I4T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-5712ACDL3-I4T1U",
  "weight": 0.035
 },
 {
  "partNo": "S-5712BNDH3-I4T1U",
  "weight": 0.018
 },
 {
  "partNo": "S-5715DNSL1-M3T1U",
  "weight": 0.03
 },
 {
  "partNo": "S-5716ACDL1-M3T1U",
  "weight": 0.03
 },
 {
  "partNo": "S-5716ACSL1-I4T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-5716ANDL1-M3T1U",
  "weight": 0.033333
 },
 {
  "partNo": "S-5716ANSL1-I4T1U",
  "weight": 0.018
 },
 {
  "partNo": "S-5814A-I4T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-77100A02-I8T1U4",
  "weight": 0.024
 },
 {
  "partNo": "S-80830CNMC-B8PT2G",
  "weight": 0.03
 },
 {
  "partNo": "S-80830CNMC-B8PT2U",
  "weight": 0.036
 },
 {
  "partNo": "S-80860CNNB-B9LT2G",
  "weight": 0.026
 },
 {
  "partNo": "S-80860CNNB-B9LT2U",
  "weight": 0.03
 },
 {
  "partNo": "S-80929CNMC-G8ZT2U",
  "weight": 0.036
 },
 {
  "partNo": "S-80930CNMC-G80T2G",
  "weight": 0.04
 },
 {
  "partNo": "S-80930CNMC-G80T2U",
  "weight": 0.036667
 },
 {
  "partNo": "S-80946CNMC-G9GT2G",
  "weight": 0.036667
 },
 {
  "partNo": "S-80946CNMC-G9GT2U",
  "weight": 0.036667
 },
 {
  "partNo": "S-812C30AMC-C2KT2G",
  "weight": 0.033333
 },
 {
  "partNo": "S-812C30AMC-C2KT2U",
  "weight": 0.033333
 },
 {
  "partNo": "S-812C30AUA-C2KT2G",
  "weight": 0.13
 },
 {
  "partNo": "S-812C30AY-Z2-U",
  "weight": 0.33
 },
 {
  "partNo": "S-812C33AMC-C2NT2G",
  "weight": 0.033333
 },
 {
  "partNo": "S-812C33AMC-C2NT2U",
  "weight": 0.033333
 },
 {
  "partNo": "S-812C33AUA-C2NT2U",
  "weight": 0.12
 },
 {
  "partNo": "S-812C50AMC-C3ET2U",
  "weight": 0.04
 },
 {
  "partNo": "S-816A33AMC-BAIT2G",
  "weight": 0.033333
 },
 {
  "partNo": "EKXJ201ELL331MMN3S",
  "weight": 13.76
 },
 {
  "partNo": "S-816A33AMC-BAIT2U",
  "weight": 0.036
 },
 {
  "partNo": "S-817B15AMC-CWET2U",
  "weight": 0.03
 },
 {
  "partNo": "S-8200AAD-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-8211DBB-M5T1U",
  "weight": 0.04
 },
 {
  "partNo": "S-8215AAI-K8T2U",
  "weight": 0.045
 },
 {
  "partNo": "S-8215BAF-K8T2U",
  "weight": 0.0425
 },
 {
  "partNo": "S-8240AAD-A6T2U",
  "weight": 0.02
 },
 {
  "partNo": "S-8240ABF-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-8240ACP-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-8240ADJ-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-8240AFL-I6T1U7",
  "weight": 0.02
 },
 {
  "partNo": "S-8244AAOFM-CEOT2U",
  "weight": 0.045
 },
 {
  "partNo": "S-8261AAJMD-G2JT2G",
  "weight": 0.036667
 },
 {
  "partNo": "S-8261AAJMD-G2JT2U",
  "weight": 0.036667
 },
 {
  "partNo": "S-8261AALMD-G2LT2U",
  "weight": 0.03
 },
 {
  "partNo": "S-8261ABJMD-G3JT2U",
  "weight": 0.036
 },
 {
  "partNo": "S-8261ABKMD-G3KT2G",
  "weight": 0.036
 },
 {
  "partNo": "S-82A1ABV-A6T5S",
  "weight": 0.024
 },
 {
  "partNo": "S-82B1BAA-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-82D1AAP-A8T2U7",
  "weight": 0.02
 },
 {
  "partNo": "S-82N1BAA-I6T1U",
  "weight": 0.02
 },
 {
  "partNo": "S-8353A33MC-IQST2G",
  "weight": 0.03
 },
 {
  "partNo": "S-8353A33MC-IQST2U",
  "weight": 0.036667
 },
 {
  "partNo": "S-8353H30MC-IWPT2G",
  "weight": 0.036667
 },
 {
  "partNo": "S-8353H30MC-IWPT2U",
  "weight": 0.036667
 },
 {
  "partNo": "S-8354A50MC-JRJT2U",
  "weight": 0.04
 },
 {
  "partNo": "S-8365ABBBA-I6T1U2",
  "weight": 0.024
 },
 {
  "partNo": "S-8366ABABA-M5T1U2",
  "weight": 0.03
 },
 {
  "partNo": "S-873325BUP-ALAT2G",
  "weight": 0.14
 },
 {
  "partNo": "S-873325BUP-ALAT2U",
  "weight": 0.15
 },
 {
  "partNo": "S-882145AMH-M2UTFU",
  "weight": 0.043333
 },
 {
  "partNo": "S-89531ACNC-HCCTFU",
  "weight": 0.03
 },
 {
  "partNo": "S-93C46BD0I-J8T1U",
  "weight": 0.17
 },
 {
  "partNo": "SDS7000EF",
  "weight": 0.0275
 },
 {
  "partNo": "SN7805D",
  "weight": 0.48
 },
 {
  "partNo": "SN7805PI",
  "weight": 2
 },
 {
  "partNo": "09077950/RMSN32-31A-1.93-P-S-G200",
  "weight": 17.5
 },
 {
  "partNo": "09077953",
  "weight": 20
 },
 {
  "partNo": "TM8723-383",
  "weight": 0.02
 },
 {
  "partNo": "CL-SB-13C-12",
  "weight": 0.4
 },
 {
  "partNo": "ATE1D-2M3-10-Z",
  "weight": 2.291
 },
 {
  "partNo": "CAS-120TA1",
  "weight": 0.28
 },
 {
  "partNo": "CAS-120TB",
  "weight": 0.25
 },
 {
  "partNo": "CAS-220TA1",
  "weight": 0.3
 },
 {
  "partNo": "ELXZ350EC3122ML20S",
  "weight": 13.8
 },
 {
  "partNo": "CAS-D20TA",
  "weight": 0.24
 },
 {
  "partNo": "CF-LB-1AL-4AG",
  "weight": 11.5
 },
 {
  "partNo": "CFP-0402TB",
  "weight": 1.52
 },
 {
  "partNo": "CFP-0802TB",
  "weight": 2.44
 },
 {
  "partNo": "CFS-0103TB",
  "weight": 0.6
 },
 {
  "partNo": "CFS-0200TB",
  "weight": 0.65
 },
 {
  "partNo": "CFS-0202MC",
  "weight": 0.48
 },
 {
  "partNo": "CFS-0203MC",
  "weight": 0.5
 },
 {
  "partNo": "CFS-0401TB",
  "weight": 0.95
 },
 {
  "partNo": "CFS-0402MC",
  "weight": 1
 },
 {
  "partNo": "CFS-0403TB",
  "weight": 0.875
 },
 {
  "partNo": "CFS-0800TA",
  "weight": 1.27
 },
 {
  "partNo": "CFS-0801TA",
  "weight": 1.26
 },
 {
  "partNo": "CFS-0803TB",
  "weight": 1.4375
 },
 {
  "partNo": "CHP-040TA",
  "weight": 0.68
 },
 {
  "partNo": "CHP-041TA",
  "weight": 0.64
 },
 {
  "partNo": "CHP-081TA",
  "weight": 0.84
 },
 {
  "partNo": "CHS-01A1",
  "weight": 0.2
 },
 {
  "partNo": "CHS-01TA",
  "weight": 0.22
 },
 {
  "partNo": "CHS-01TA1",
  "weight": 0.3
 },
 {
  "partNo": "CHS-01TB2",
  "weight": 0.22
 },
 {
  "partNo": "CHS-02TA",
  "weight": 0.4
 },
 {
  "partNo": "CHS-02TA1",
  "weight": 0.48
 },
 {
  "partNo": "CHS-02TB1",
  "weight": 0.4
 },
 {
  "partNo": "CHS-02TB2",
  "weight": 0.4
 },
 {
  "partNo": "CHS-04TA",
  "weight": 0.6
 },
 {
  "partNo": "CHS-04TA1",
  "weight": 0.52
 },
 {
  "partNo": "CHS-04TA2",
  "weight": 0.44
 },
 {
  "partNo": "CHS-04TB",
  "weight": 0.54
 },
 {
  "partNo": "CHS-04TB(7)",
  "weight": 0.52
 },
 {
  "partNo": "CHS-04TB1",
  "weight": 0.5
 },
 {
  "partNo": "CHS-08TB",
  "weight": 0.6
 },
 {
  "partNo": "CHS-08TB2",
  "weight": 0.68
 },
 {
  "partNo": "CJ25-42011A",
  "weight": 19.4
 },
 {
  "partNo": "CJS-1200TA1",
  "weight": 0.26
 },
 {
  "partNo": "CL-SB-22A-02T",
  "weight": 0.8
 },
 {
  "partNo": "CL-SB-22A-11T",
  "weight": 0.96
 },
 {
  "partNo": "CMS-4202TB",
  "weight": 1.48
 },
 {
  "partNo": "AFS450V105K",
  "weight": 2.4
 },
 {
  "partNo": "AFS450V474K",
  "weight": 1.65
 },
 {
  "partNo": "CRFS-2202W",
  "weight": 2.16
 },
 {
  "partNo": "CRV16-60",
  "weight": 5.79
 },
 {
  "partNo": "CT-94EW103",
  "weight": 1
 },
 {
  "partNo": "CT-9EW503",
  "weight": 1.2
 },
 {
  "partNo": "CUS-12TB",
  "weight": 0.2
 },
 {
  "partNo": "CFPS1/2CT52A104J",
  "weight": 0.285
 },
 {
  "partNo": "CVS-04TB",
  "weight": 0.2
 },
 {
  "partNo": "CWS-0203MC",
  "weight": 0.5
 },
 {
  "partNo": "CWS-0603MC",
  "weight": 1.5
 },
 {
  "partNo": "DP7119SDI-00-GT3",
  "weight": 0.03
 },
 {
  "partNo": "RJ-5EX502",
  "weight": 0.35
 },
 {
  "partNo": "CW3PCT521AR348F",
  "weight": 1.44
 },
 {
  "partNo": "DTN-C203F3T-TSFB16A",
  "weight": 0.15
 },
 {
  "partNo": "DTN-C203F3Y-DKK140A",
  "weight": 0.26
 },
 {
  "partNo": "EKRG6R3ETD102MJ09S",
  "weight": 1.55
 },
 {
  "partNo": "EKXG201ELL221MM25S",
  "weight": 10.2
 },
 {
  "partNo": "EKZE101ETD470MJC5S",
  "weight": 1.925
 },
 {
  "partNo": "EKZH250ELL222MK30S",
  "weight": 5.9
 },
 {
  "partNo": "FPB22W105K",
  "weight": 1.6
 },
 {
  "partNo": "FMV05N50E-S25PPSC-P",
  "weight": 2.58
 },
 {
  "partNo": "IL1117-3.3",
  "weight": 0.2275
 },
 {
  "partNo": "JC202PC2",
  "weight": 3.64
 },
 {
  "partNo": "HPC1/2C6R8M",
  "weight": 0.81
 },
 {
  "partNo": "SR732BTTDR365F",
  "weight": 0.028
 },
 {
  "partNo": "SR732BTTDR845F",
  "weight": 0.028
 },
 {
  "partNo": "SR733ATTER200F",
  "weight": 0.06
 },
 {
  "partNo": "WF7NC10G100J",
  "weight": 10.8
 },
 {
  "partNo": "BPR58CL4515LJ",
  "weight": 2.02
 },
 {
  "partNo": "LE104-M",
  "weight": 1.3
 },
 {
  "partNo": "LE104-MX",
  "weight": 1.18
 },
 {
  "partNo": "LE105",
  "weight": 7.2
 },
 {
  "partNo": "LE105-C3.5",
  "weight": 7.2
 },
 {
  "partNo": "LE105-MX",
  "weight": 5.8
 },
 {
  "partNo": "LE105-MX-C3.5",
  "weight": 2.85
 },
 {
  "partNo": "LE224",
  "weight": 2.3
 },
 {
  "partNo": "DP7119SDI-10-GT3",
  "weight": 0.03
 },
 {
  "partNo": "LE224-MX",
  "weight": 1.81
 },
 {
  "partNo": "LE225",
  "weight": 16.8
 },
 {
  "partNo": "LE334-M",
  "weight": 2.8
 },
 {
  "partNo": "LE334-MX",
  "weight": 2.5
 },
 {
  "partNo": "LE474",
  "weight": 4.18
 },
 {
  "partNo": "LE474-MX-C3.5",
  "weight": 3.36
 },
 {
  "partNo": "LE684",
  "weight": 5.6
 },
 {
  "partNo": "APXA4R0ARA151MF60G",
  "weight": 0.69
 },
 {
  "partNo": "APXA6R3ARA101MF60G",
  "weight": 0.68
 },
 {
  "partNo": "BKRE500ELL2R2ME05D",
  "weight": 0.3
 },
 {
  "partNo": "ECST401ELL151MM40S",
  "weight": 17.48
 },
 {
  "partNo": "EFL-160ELL470MF05D",
  "weight": 0.4
 },
 {
  "partNo": "EFL-6R3ELL101MF05D",
  "weight": 0.405
 },
 {
  "partNo": "EGPA350EC3102MK25S",
  "weight": 4.98
 },
 {
  "partNo": "EGPA350EC3122MK30S",
  "weight": 6
 },
 {
  "partNo": "EGXL350ELL331MJ20S",
  "weight": 2.66
 },
 {
  "partNo": "EKLJ451ELL820MMN3S",
  "weight": 16.7
 },
 {
  "partNo": "EKMG101ELL221MK25S",
  "weight": 4.58
 },
 {
  "partNo": "EKMG101ETD101MJ20S",
  "weight": 2.625
 },
 {
  "partNo": "EKMG160ETC100ME11D",
  "weight": 0.59
 },
 {
  "partNo": "EKMG160ETC220ME11D",
  "weight": 0.6
 },
 {
  "partNo": "EKMG250ELL101MF11D",
  "weight": 0.71
 },
 {
  "partNo": "EKMG250ELL332ML25S",
  "weight": 8.04
 },
 {
  "partNo": "EKMG250ETC100ME11D",
  "weight": 0.595
 },
 {
  "partNo": "EKMG250ETC470ME11D",
  "weight": 0.62
 },
 {
  "partNo": "EKMG350ELL471MJ16S",
  "weight": 2.1
 },
 {
  "partNo": "EKMG350ETC221MHB5D",
  "weight": 1.36
 },
 {
  "partNo": "EKMG350ETD101MF11D",
  "weight": 0.81
 },
 {
  "partNo": "EKMG500ETC100ME11D",
  "weight": 0.62
 },
 {
  "partNo": "EKMG500ETC2R2ME11D",
  "weight": 0.58
 },
 {
  "partNo": "EKMG500ETC470MF11D",
  "weight": 0.84
 },
 {
  "partNo": "EKMG630ETD100ME11D",
  "weight": 0.58
 },
 {
  "partNo": "EKMM201VSN471MP35S",
  "weight": 19.45
 },
 {
  "partNo": "EKMQ201VSN391MP25S",
  "weight": 16.35
 },
 {
  "partNo": "EKMQ421VSN181MQ30S",
  "weight": 22.7
 },
 {
  "partNo": "EKMR401VSN181MQ25S-T",
  "weight": 21.7
 },
 {
  "partNo": "EKRE160ETC100MD05D",
  "weight": 0.31
 },
 {
  "partNo": "EKRE250ETC100ME05D",
  "weight": 0.39
 },
 {
  "partNo": "EKXG201ELL220MJ20S",
  "weight": 2.38
 },
 {
  "partNo": "EKXG401ELL101MMN3S",
  "weight": 12.68
 },
 {
  "partNo": "EKXG401ELL151MMP1S",
  "weight": 16.28
 },
 {
  "partNo": "EKXG401ELL220MK20S",
  "weight": 4.26
 },
 {
  "partNo": "EKXG401ELL330ML20S",
  "weight": 6.32
 },
 {
  "partNo": "EKXG421ELL820MM25S",
  "weight": 11.76
 },
 {
  "partNo": "EKXJ251ELL121ML25S",
  "weight": 9.12
 },
 {
  "partNo": "EKXJ351ELL121MLP1S",
  "weight": 11.8
 },
 {
  "partNo": "EKXJ351ELL221MM45S",
  "weight": 19.84
 },
 {
  "partNo": "EKXJ401EC3151MM40S",
  "weight": 18.04
 },
 {
  "partNo": "EKXJ401EC3680MK40S",
  "weight": 8.8
 },
 {
  "partNo": "EKXJ401ELL390MK25S",
  "weight": 5.44
 },
 {
  "partNo": "EKXJ401ELL560MU25S",
  "weight": 7.64
 },
 {
  "partNo": "EKY-160ELL222MK25S",
  "weight": 4.88
 },
 {
  "partNo": "EKY-250ELL152MK25S",
  "weight": 5.14
 },
 {
  "partNo": "EKY-250ETD102MK20S",
  "weight": 4.08
 },
 {
  "partNo": "EKY-500ELL100ME11D",
  "weight": 0.52
 },
 {
  "partNo": "EKY-500ELL101MHB5D",
  "weight": 1.25
 },
 {
  "partNo": "EKY-500ELL471MJ30S",
  "weight": 3.54
 },
 {
  "partNo": "EKY-500ETD100ME11D",
  "weight": 0.6
 },
 {
  "partNo": "EKY-500ETD101MHB5D",
  "weight": 1.34
 },
 {
  "partNo": "EKY-500ETD220ME11D",
  "weight": 0.61
 },
 {
  "partNo": "EKY-500ETD560MF11D",
  "weight": 0.845
 },
 {
  "partNo": "EKY-630ELL821MLN3S",
  "weight": 9.72
 },
 {
  "partNo": "EKY-630ETD121MJ16S",
  "weight": 2.275
 },
 {
  "partNo": "EKY-630ETD150ME11D",
  "weight": 0.64
 },
 {
  "partNo": "EKY-6R3ELL102MH15D",
  "weight": 1.4
 },
 {
  "partNo": "EKZE101ELL221MK25S",
  "weight": 5.32
 },
 {
  "partNo": "EKZE101ELL331ML25S",
  "weight": 8.16
 },
 {
  "partNo": "EKZE250ETD221MHB5D",
  "weight": 1.3
 },
 {
  "partNo": "EKZE250ETD471MJ16S",
  "weight": 2.2
 },
 {
  "partNo": "EKZH160ELL222MK20S",
  "weight": 4.24
 },
 {
  "partNo": "EKZH250ETD681MJ16S",
  "weight": 2.325
 },
 {
  "partNo": "EKZH350ELL561MJ20S",
  "weight": 2.7
 },
 {
  "partNo": "EKZM350EC3122MK25S",
  "weight": 5.4
 },
 {
  "partNo": "EKZN160ELL182MJ25S",
  "weight": 3.73
 },
 {
  "partNo": "EKZN160ELL471MHB5D",
  "weight": 1.28
 },
 {
  "partNo": "EKZN160ELL472ML25S",
  "weight": 8.2
 },
 {
  "partNo": "EKZN350EC3471MJ20S",
  "weight": 2.96
 },
 {
  "partNo": "EKZN350ETC221MH15D",
  "weight": 1.64
 },
 {
  "partNo": "EKZN630EC3101MH15D",
  "weight": 1.42
 },
 {
  "partNo": "ELXS401VSN181MQ25S",
  "weight": 22.8
 },
 {
  "partNo": "ELXZ100EC3562ML25S",
  "weight": 7.44
 },
 {
  "partNo": "ELXZ160EC3222MK25S",
  "weight": 5.32
 },
 {
  "partNo": "EMVA160ADA221MF80G",
  "weight": 0.688889
 },
 {
  "partNo": "EMVA160ADA471MHA0G",
  "weight": 1.38
 },
 {
  "partNo": "EMVA250ADA100MD55G",
  "weight": 0.235
 },
 {
  "partNo": "EMVA500ADA101MHA0G",
  "weight": 1.4
 },
 {
  "partNo": "EMVA500ADA470MF80G",
  "weight": 0.7
 },
 {
  "partNo": "EMVA630ADA1R0MD55G",
  "weight": 0.24
 },
 {
  "partNo": "EMZA350ADA101MF80G",
  "weight": 0.7
 },
 {
  "partNo": "ESMG160ETC101ME11D",
  "weight": 0.61
 },
 {
  "partNo": "ESMG250ETD471MJC5S",
  "weight": 1.875
 },
 {
  "partNo": "ESMG500ETC100ME11D",
  "weight": 0.6
 },
 {
  "partNo": "ESMG500ETC220ME11D",
  "weight": 0.6
 },
 {
  "partNo": "NX3225SA-12.000M-STD-CSR-6",
  "weight": 0.04
 },
 {
  "partNo": "NX8045GB-19.6608M-STD-CSF-4",
  "weight": 0.28
 },
 {
  "partNo": "RA-302M-C6-Y",
  "weight": 0.62
 },
 {
  "partNo": "RA-311M-C6-Y",
  "weight": 0.52
 },
 {
  "partNo": "PA334-L",
  "weight": 6.4
 },
 {
  "partNo": "RC23",
  "weight": 19
 },
 {
  "partNo": "RE1201",
  "weight": 2.6
 },
 {
  "partNo": "RK73B2BTTD391J",
  "weight": 0.028
 },
 {
  "partNo": "SSP-T7-F(20PPM/12.5PF)",
  "weight": 0.06
 },
 {
  "partNo": "DECASMDC050F/60-2",
  "weight": 0.045
 },
 {
  "partNo": "SMD050F-2",
  "weight": 0.12
 },
 {
  "partNo": "V6-S-DC24V",
  "weight": 9.6
 },
 {
  "partNo": "VT-200-F(20PPM/12.5PF)",
  "weight": 0.068
 },
 {
  "partNo": "YF223",
  "weight": 1.85
 },
 {
  "partNo": "P-2000-501G-15-BN-001",
  "weight": 2.4
 },
 {
  "partNo": "PRCP-MSMF075/24-2E",
  "weight": 0.08
 },
 {
  "partNo": "PRCP-NSMF035-2E",
  "weight": 0.03
 },
 {
  "partNo": "PRCP-R135-0-99",
  "weight": 0.3
 },
 {
  "partNo": "PRCP-RX185/72-0",
  "weight": 0.96
 },
 {
  "partNo": "PRCP-SM100/33-2-99",
  "weight": 0.65
 },
 {
  "partNo": "RJ-6P102",
  "weight": 0.6
 },
 {
  "partNo": "S-1010A",
  "weight": 0.9
 },
 {
  "partNo": "S-1030A",
  "weight": 0.8
 },
 {
  "partNo": "S-7071EWC",
  "weight": 1.2
 },
 {
  "partNo": "SA-7150TB-9",
  "weight": 0.88
 },
 {
  "partNo": "SA-7271TB",
  "weight": 1.28
 },
 {
  "partNo": "SC-1031W",
  "weight": 1.5
 },
 {
  "partNo": "SD-2010W",
  "weight": 1.4
 },
 {
  "partNo": "SD-2011",
  "weight": 0.6
 },
 {
  "partNo": "SH-7050TA",
  "weight": 0.98
 },
 {
  "partNo": "SH-7070TB",
  "weight": 0.98
 },
 {
  "partNo": "SLE210K4-6",
  "weight": 7.1
 },
 {
  "partNo": "ST-4ETA",
  "weight": 0.22
 },
 {
  "partNo": "ST-7ETA201",
  "weight": 0.7
 },
 {
  "partNo": "BDH63",
  "weight": 1.5
 },
 {
  "partNo": "BL10(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL13(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL16(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL20(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL25(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL32(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL50(T)",
  "weight": 1.5625
 },
 {
  "partNo": "BL63(T)",
  "weight": 1.5625
 },
 {
  "partNo": "CRA120A:CUF4.7LM",
  "weight": 2.02
 },
 {
  "partNo": "DCP05",
  "weight": 1
 },
 {
  "partNo": "ESB5R-15000:F4.7LM",
  "weight": 2.76
 },
 {
  "partNo": "HHA18A:F4.7",
  "weight": 2.6
 },
 {
  "partNo": "KMS16",
  "weight": 0.0266
 },
 {
  "partNo": "KMS20",
  "weight": 0.023
 },
 {
  "partNo": "KMS32",
  "weight": 0.0266
 },
 {
  "partNo": "KMS40",
  "weight": 0.0266
 },
 {
  "partNo": "KMS50",
  "weight": 0.033
 },
 {
  "partNo": "KMS71",
  "weight": 0.03
 },
 {
  "partNo": "KMS80",
  "weight": 0.023
 },
 {
  "partNo": "MP05",
  "weight": 2.2
 },
 {
  "partNo": "MP10",
  "weight": 2.45
 },
 {
  "partNo": "MP16",
  "weight": 2.4
 },
 {
  "partNo": "ULCS-61M2",
  "weight": 1.65
 },
 {
  "partNo": "1N4006",
  "weight": 0.3
 },
 {
  "partNo": "1N4007",
  "weight": 0.3
 },
 {
  "partNo": "B80D",
  "weight": 0.6
 },
 {
  "partNo": "BAV21",
  "weight": 0.1
 },
 {
  "partNo": "BAV21WS",
  "weight": 0.02
 },
 {
  "partNo": "BC547BBK",
  "weight": 0.2
 },
 {
  "partNo": "BC846C",
  "weight": 0.026667
 },
 {
  "partNo": "DBI25-16A",
  "weight": 12.9
 },
 {
  "partNo": "DI280N10TL",
  "weight": 0.86
 },
 {
  "partNo": "EGL1B",
  "weight": 0.056
 },
 {
  "partNo": "ER1D-AQ",
  "weight": 0.1
 },
 {
  "partNo": "ES2D",
  "weight": 0.186
 },
 {
  "partNo": "GBU8K",
  "weight": 3.98
 },
 {
  "partNo": "GL1G",
  "weight": 0.06
 },
 {
  "partNo": "GL1J",
  "weight": 0.06
 },
 {
  "partNo": "GL34M",
  "weight": 0.06
 },
 {
  "partNo": "KBPC810",
  "weight": 5.8
 },
 {
  "partNo": "MM1Z4733A",
  "weight": 0.033
 },
 {
  "partNo": "MM3Z9V1",
  "weight": 0.02
 },
 {
  "partNo": "MM5ZB47",
  "weight": 0.0175
 },
 {
  "partNo": "MMBT7002K",
  "weight": 0.026
 },
 {
  "partNo": "MPSA44",
  "weight": 0.275
 },
 {
  "partNo": "P4SMAJ28A",
  "weight": 0.1
 },
 {
  "partNo": "P6SMBJ30CA",
  "weight": 0.183
 },
 {
  "partNo": "S1G",
  "weight": 0.098
 },
 {
  "partNo": "S250",
  "weight": 0.148
 },
 {
  "partNo": "S3W",
  "weight": 0.39
 },
 {
  "partNo": "SGL1-30",
  "weight": 0.06
 },
 {
  "partNo": "SK26",
  "weight": 0.186667
 },
 {
  "partNo": "SK34SMA-3G",
  "weight": 0.104
 },
 {
  "partNo": "SL1M",
  "weight": 0.04
 },
 {
  "partNo": "SM4003",
  "weight": 0.17
 },
 {
  "partNo": "SM4004",
  "weight": 0.172
 },
 {
  "partNo": "SM4006",
  "weight": 0.17
 },
 {
  "partNo": "SM4007",
  "weight": 0.18
 },
 {
  "partNo": "SMF51CA",
  "weight": 0.033333
 },
 {
  "partNo": "SMS140",
  "weight": 0.164
 },
 {
  "partNo": "SUF4004",
  "weight": 0.17
 },
 {
  "partNo": "Z1SMA10",
  "weight": 0.106
 },
 {
  "partNo": "ZY200",
  "weight": 0.38
 },
 {
  "partNo": "SK36SMB",
  "weight": 0.193
 },
 {
  "partNo": "EKZE350ELL331MJ16S",
  "weight": 2.06
 },
 {
  "partNo": "EKZE350ELL471MJ20S",
  "weight": 2.52
 },
 {
  "partNo": "ELXS421VSN391MR40S",
  "weight": 46.4
 },
 {
  "partNo": "EMZA250ARA221MHA0G",
  "weight": 1.5
 },
 {
  "partNo": "EMZA6R3ARA101ME61G",
  "weight": 0.5
 },
 {
  "partNo": "EPAG401ELL101MM25S",
  "weight": 11.12
 },
 {
  "partNo": "TGS5141-P00",
  "weight": 2.75
 },
 {
  "partNo": "ESAD83-006R",
  "weight": 5.36
 },
 {
  "partNo": "FMV60N280S2HF",
  "weight": 2.6
 },
 {
  "partNo": "PA905C4R",
  "weight": 5.36
 },
 {
  "partNo": "YA865C15R-S25PPSC-P",
  "weight": 3
 },
 {
  "partNo": "HF-C7140",
  "weight": 2.6
 },
 {
  "partNo": "IC-DPSOT23-6L",
  "weight": 0.05
 },
 {
  "partNo": "IC-HFQFN32-5X5",
  "weight": 0.5
 },
 {
  "partNo": "IC-HGQFN285X5",
  "weight": 0.11
 },
 {
  "partNo": "IC-HG30EVALHG1D",
  "weight": 40
 },
 {
  "partNo": "IC-HTQFN28-5X5",
  "weight": 0.127202
 },
 {
  "partNo": "IC-LQNPTO18-4F",
  "weight": 0.4
 },
 {
  "partNo": "IC-MB3ICSYMB3U-I2C",
  "weight": 100
 },
 {
  "partNo": "IC-MB5ICSYMB5U",
  "weight": 200
 },
 {
  "partNo": "IC-MLTSSOP20",
  "weight": 0.21
 },
 {
  "partNo": "IC-MUDFN16-5X5",
  "weight": 0.09
 },
 {
  "partNo": "IC-MUEVALMU1D",
  "weight": 70
 },
 {
  "partNo": "IC-MUQFN48-7X7",
  "weight": 1
 },
 {
  "partNo": "IC-MU150DFN16-5X5",
  "weight": 0.09
 },
 {
  "partNo": "IC-MU150EVALMU1M",
  "weight": 80
 },
 {
  "partNo": "IC-MU150QFN48-7X7",
  "weight": 1
 },
 {
  "partNo": "IC-MU200EVALMU6M",
  "weight": 80
 },
 {
  "partNo": "IC-MU200QFN48-7X7",
  "weight": 1.8
 },
 {
  "partNo": "IC-MU200X1QFN48-7X7",
  "weight": 0.16
 },
 {
  "partNo": "IC-NQC5TSSOP20",
  "weight": 0.6
 },
 {
  "partNo": "IC-NQC5T1TSSOP20",
  "weight": 0.6
 },
 {
  "partNo": "IC-NQCEVALNQ6D",
  "weight": 25
 },
 {
  "partNo": "IC-NQITSSOP20",
  "weight": 1.31
 },
 {
  "partNo": "IC-NZNEVALNZN1D",
  "weight": 90
 },
 {
  "partNo": "IC-NZNQFN24-4X4",
  "weight": 0.088
 },
 {
  "partNo": "IC-PITSSOP20",
  "weight": 0.21
 },
 {
  "partNo": "IC-PR4307OQFN24-4X4",
  "weight": 0.86
 },
 {
  "partNo": "IC-PZEVALPZ2D",
  "weight": 120
 },
 {
  "partNo": "IC-PZ205OQFN32-5X5",
  "weight": 0.2
 },
 {
  "partNo": "IC-PZ2656EVALPZ1M",
  "weight": 70
 },
 {
  "partNo": "IC-SD85BLCCSD1C",
  "weight": 0.15
 },
 {
  "partNo": "IC-SM2LLGASM2C",
  "weight": 0.61
 },
 {
  "partNo": "IC-TW8QFN48-7X7",
  "weight": 0.3125
 },
 {
  "partNo": "IC-VRVPLCC44",
  "weight": 5
 },
 {
  "partNo": "IC-WKLMSOP8",
  "weight": 0.1
 },
 {
  "partNo": "IC-WKNSO8-TP",
  "weight": 0.41
 },
 {
  "partNo": "MU28S34-32N",
  "weight": 8
 },
 {
  "partNo": "PZ05SM69-1024",
  "weight": 20
 },
 {
  "partNo": "PZ08SM44-446",
  "weight": 25
 },
 {
  "partNo": "IC-MHMQFN28-5X5",
  "weight": 0.13698
 },
 {
  "partNo": "IC-NQCTSSOP20",
  "weight": 2
 },
 {
  "partNo": "IC-NQIV3TSSOP20",
  "weight": 0.8
 },
 {
  "partNo": "IL1117C-3.3",
  "weight": 0.2275
 },
 {
  "partNo": "IL2904DT",
  "weight": 0.26
 },
 {
  "partNo": "IL34063ADT",
  "weight": 0.224
 },
 {
  "partNo": "IL34119DT",
  "weight": 0.248
 },
 {
  "partNo": "IL6965DT",
  "weight": 0.56
 },
 {
  "partNo": "IL6965N",
  "weight": 2.222222
 },
 {
  "partNo": "5D2-07LD",
  "weight": 0.98
 },
 {
  "partNo": "E-202-52Z",
  "weight": 0.164
 },
 {
  "partNo": "ED2F103A2-81046",
  "weight": 0.25
 },
 {
  "partNo": "S-202T",
  "weight": 0.023333
 },
 {
  "partNo": "S-562T",
  "weight": 0.023333
 },
 {
  "partNo": "103AT-2(DIA88020)",
  "weight": 0.09
 },
 {
  "partNo": "103CT-4",
  "weight": 0.13
 },
 {
  "partNo": "103KT1005T-1P",
  "weight": 0.007
 },
 {
  "partNo": "103NT-4-R025H41G",
  "weight": 0.05
 },
 {
  "partNo": "10D2-15LC",
  "weight": 2.7
 },
 {
  "partNo": "15D2-13LC",
  "weight": 2
 },
 {
  "partNo": "16D-13",
  "weight": 2.1
 },
 {
  "partNo": "1D2-15LCS",
  "weight": 1.6
 },
 {
  "partNo": "3D2-10LCS",
  "weight": 0.8
 },
 {
  "partNo": "5D2-08LCS",
  "weight": 0.8
 },
 {
  "partNo": "5D2-15LD",
  "weight": 2.68
 },
 {
  "partNo": "ET6F103JT-09T051",
  "weight": 2.4
 },
 {
  "partNo": "M5R110C(DJA91077)",
  "weight": 1
 },
 {
  "partNo": "S-152T",
  "weight": 0.023
 },
 {
  "partNo": "S-301T",
  "weight": 0.023
 },
 {
  "partNo": "S-701T",
  "weight": 0.023
 },
 {
  "partNo": "SG-105F",
  "weight": 0.05
 },
 {
  "partNo": "KED941M51C",
  "weight": 0.28
 },
 {
  "partNo": "KPD3212",
  "weight": 4
 },
 {
  "partNo": "MPU12272MLBO",
  "weight": 0.095
 },
 {
  "partNo": "MPU12371MLBO",
  "weight": 0.095
 },
 {
  "partNo": "BN35-3Y203FB-CGD101A",
  "weight": 0.24
 },
 {
  "partNo": "BN35-3Y203FB-DKK333A",
  "weight": 0.18
 },
 {
  "partNo": "TD05-3H103FR",
  "weight": 0.015
 },
 {
  "partNo": "M1003S103",
  "weight": 0.16
 },
 {
  "partNo": "M1007S165",
  "weight": 0.21
 },
 {
  "partNo": "EKMQ421VSN471MR45S",
  "weight": 50.2
 },
 {
  "partNo": "APS-200ELL101MHB5S",
  "weight": 1.06
 },
 {
  "partNo": "APS-350ETD180MHB5S",
  "weight": 1.07
 },
 {
  "partNo": "APS-350ETD330MJC5S",
  "weight": 1.7
 },
 {
  "partNo": "APSA100EC3471MJB5S",
  "weight": 1.4
 },
 {
  "partNo": "APSA100ELL471MJB5S",
  "weight": 1.58
 },
 {
  "partNo": "APSC160ETD271MHB5S",
  "weight": 1.04
 },
 {
  "partNo": "APSC2R5EC3122MH081",
  "weight": 0.68
 },
 {
  "partNo": "APSC2R5ELL102MH08S",
  "weight": 0.75
 },
 {
  "partNo": "APSC4R0ETD561MH08S",
  "weight": 0.8
 },
 {
  "partNo": "APSC6R3EC3561MH08S",
  "weight": 0.62
 },
 {
  "partNo": "APSC6R3ETD561MH08S",
  "weight": 0.84
 },
 {
  "partNo": "APSE6R3EC3561MF08S",
  "weight": 0.5
 },
 {
  "partNo": "APSF160EC3101MF05S",
  "weight": 0.4
 },
 {
  "partNo": "APSF160ELL471MJB5S",
  "weight": 1.4
 },
 {
  "partNo": "APSF2R5EC3821MF08S",
  "weight": 0.4
 },
 {
  "partNo": "APSG160ELL102MJB5S",
  "weight": 1.52
 },
 {
  "partNo": "APSG160ELL122MH20S",
  "weight": 1.5
 },
 {
  "partNo": "APSG250ELL221MHB5S",
  "weight": 1
 },
 {
  "partNo": "APSG250ELL331MJB5S",
  "weight": 1.54
 },
 {
  "partNo": "APXA160ARA390MF60G",
  "weight": 0.68
 },
 {
  "partNo": "APXA6R3ARA221MH70G",
  "weight": 0.96
 },
 {
  "partNo": "APXA6R3ARA471MHC0G",
  "weight": 1.8
 },
 {
  "partNo": "APXE100ARA121MF61G",
  "weight": 0.67
 },
 {
  "partNo": "APXE100ARA471MJ80G",
  "weight": 1.7
 },
 {
  "partNo": "APXE100ARA560ME61G",
  "weight": 0.55
 },
 {
  "partNo": "APXE6R3ARA221MF61G",
  "weight": 0.7
 },
 {
  "partNo": "APXF2R5ARA561MF611",
  "weight": 0.7
 },
 {
  "partNo": "APXF2R5ARA561MF61G",
  "weight": 0.72
 },
 {
  "partNo": "APXG160ARA101ME61G",
  "weight": 0.57
 },
 {
  "partNo": "APXG160ARA102MJA0G",
  "weight": 1.93
 },
 {
  "partNo": "APXG160ARA102MJC0G",
  "weight": 2.275
 },
 {
  "partNo": "APXG160ARA181MF61G",
  "weight": 0.7
 },
 {
  "partNo": "APXG160ARA221MF80G",
  "weight": 0.8
 },
 {
  "partNo": "APXG160ARA271MH70G",
  "weight": 0.96
 },
 {
  "partNo": "APXG160ARA271MHA0G",
  "weight": 1.44
 },
 {
  "partNo": "APXG200ARA391MHA0G",
  "weight": 1.54
 },
 {
  "partNo": "APXJ160ARA271MF80G",
  "weight": 0.8
 },
 {
  "partNo": "BKMA500ETCR47MD07D",
  "weight": 0.36
 },
 {
  "partNo": "BKME101ELL101ML25S",
  "weight": 7.62
 },
 {
  "partNo": "BKME350ELL470MHB5D",
  "weight": 1.23
 },
 {
  "partNo": "BSME500ETC1R0ME11D",
  "weight": 0.64
 },
 {
  "partNo": "E32D501CDS422MFE5M",
  "weight": 1500
 },
 {
  "partNo": "E36D451HPN222MDA5U",
  "weight": 451.5
 },
 {
  "partNo": "ECST401LGC332VDA5U",
  "weight": 450
 },
 {
  "partNo": "ECST451EC3121MM30S",
  "weight": 15.3
 },
 {
  "partNo": "ECST451ELL151MM45S",
  "weight": 24.5
 },
 {
  "partNo": "ECST630ELL382MM60S",
  "weight": 27.9
 },
 {
  "partNo": "EGPA250ELL222MK30S",
  "weight": 5.9
 },
 {
  "partNo": "EGPA350ELL122MK30S",
  "weight": 5.45
 },
 {
  "partNo": "EGPA800ELL821ML40S",
  "weight": 14.16
 },
 {
  "partNo": "EGPD500ELL162MK40H",
  "weight": 9.42
 },
 {
  "partNo": "EGPD800ELL751ML30H",
  "weight": 11.4
 },
 {
  "partNo": "EGXE500ELL101MJC5S",
  "weight": 1.725
 },
 {
  "partNo": "EGXE500ELL471MK25S",
  "weight": 5
 },
 {
  "partNo": "EKHE401ELL121MMN3S",
  "weight": 13.36
 },
 {
  "partNo": "EKHF451ELL151MMN3S",
  "weight": 15.16
 },
 {
  "partNo": "EKLJ401ELL220MK20S",
  "weight": 4.2
 },
 {
  "partNo": "EKLJ451ELL121MM45S",
  "weight": 22.4
 },
 {
  "partNo": "EKMG100ELL221MF11D",
  "weight": 0.73
 },
 {
  "partNo": "EKMG101ETC2R2ME11D",
  "weight": 0.615
 },
 {
  "partNo": "EKMG160ELL100ME11D",
  "weight": 0.45
 },
 {
  "partNo": "EKMG160ELL101ME11D",
  "weight": 0.5
 },
 {
  "partNo": "EKMG160ETC221MF11D",
  "weight": 0.83
 },
 {
  "partNo": "EKMG250ETC101MF11D",
  "weight": 0.75
 },
 {
  "partNo": "EKMG250ETC221MHB5D",
  "weight": 1.26
 },
 {
  "partNo": "EKMG250ETC331MHB5D",
  "weight": 1.32
 },
 {
  "partNo": "EKMG250ETD101MF11D",
  "weight": 0.8
 },
 {
  "partNo": "EKMG250ETD471MJC5S",
  "weight": 1.975
 },
 {
  "partNo": "EKMG350ELL102MK20S",
  "weight": 4.34
 },
 {
  "partNo": "EKMG350ETC101MF11D",
  "weight": 0.82
 },
 {
  "partNo": "EKMG350ETD102MK20S",
  "weight": 4.28
 },
 {
  "partNo": "EKMG350ETD221MHB5D",
  "weight": 1.3
 },
 {
  "partNo": "EKMG401ETD2R2MHB5D",
  "weight": 1.34
 },
 {
  "partNo": "EKMG451ELL100MK20S",
  "weight": 3.66
 },
 {
  "partNo": "EKMG500ELL101MHB5D",
  "weight": 1.28
 },
 {
  "partNo": "EKMG500ETC1R0ME11D",
  "weight": 0.615
 },
 {
  "partNo": "EKMG500ETC220ME11D",
  "weight": 0.61
 },
 {
  "partNo": "EKMG500ETC4R7ME11D",
  "weight": 0.63
 },
 {
  "partNo": "EKMG500ETCR47ME11D",
  "weight": 0.6
 },
 {
  "partNo": "EKMG500ETD1R0ME11D",
  "weight": 0.615
 },
 {
  "partNo": "EKMG500ETD471MJ20S",
  "weight": 2.825
 },
 {
  "partNo": "EKMG6R3ETC471MF11D",
  "weight": 0.82
 },
 {
  "partNo": "EKMG6R3ETD472MK20S",
  "weight": 4.52
 },
 {
  "partNo": "EKMH500VSN472MP45S",
  "weight": 22
 },
 {
  "partNo": "EKMM401VSN121MQ25S",
  "weight": 17.3
 },
 {
  "partNo": "EKMM401VSN271MQ45S",
  "weight": 31
 },
 {
  "partNo": "EKMM401VSN331MQ50S",
  "weight": 36.15
 },
 {
  "partNo": "EKMQ100ELL472MK25S",
  "weight": 4.95
 },
 {
  "partNo": "EKMQ101ELL101MJ16S",
  "weight": 2.25
 },
 {
  "partNo": "EKMQ101ETD470MHB5D",
  "weight": 1.34
 },
 {
  "partNo": "EKMQ160ELL102MJC5S",
  "weight": 1.8
 },
 {
  "partNo": "EKMQ160ELL222MJ20S",
  "weight": 2.675
 },
 {
  "partNo": "EKMQ160ETD682ML25S",
  "weight": 9.16
 },
 {
  "partNo": "EKMQ161ELL101MK25S",
  "weight": 4.89
 },
 {
  "partNo": "EKMQ201VSN102MP50S",
  "weight": 32.55
 },
 {
  "partNo": "EKMQ201VSN152MA30W",
  "weight": 51.25
 },
 {
  "partNo": "EKMQ201VSN471MP30S",
  "weight": 18.75
 },
 {
  "partNo": "EKMQ250ELL221MF11D",
  "weight": 0.755
 },
 {
  "partNo": "EKMQ351ELL100MJC5S",
  "weight": 1.865
 },
 {
  "partNo": "EKMQ401VSN151MQ25S",
  "weight": 19.4
 },
 {
  "partNo": "EKMQ451VSN271MA30S",
  "weight": 40.45
 },
 {
  "partNo": "EKMQ451VSN391MR50S",
  "weight": 46
 },
 {
  "partNo": "EKMQ451VSN561MA50S",
  "weight": 65
 },
 {
  "partNo": "EKMR421VSN221MR25S",
  "weight": 25.7
 },
 {
  "partNo": "EKMR451VSN271MR30S",
  "weight": 35.15
 },
 {
  "partNo": "EKMR451VSN561MA40S",
  "weight": 64
 },
 {
  "partNo": "EKMR451VSN681MA50S",
  "weight": 75
 },
 {
  "partNo": "EKMS161VSN222MR45S",
  "weight": 54
 },
 {
  "partNo": "EKMS421VSN121MQ25S",
  "weight": 20.4
 },
 {
  "partNo": "EKMS421VSN271MA25S",
  "weight": 40
 },
 {
  "partNo": "EKMS421VSN271MQ40S",
  "weight": 33.85
 },
 {
  "partNo": "EKMS451VSN221MR30S",
  "weight": 34.65
 },
 {
  "partNo": "EKMW401VSN221MP35S",
  "weight": 23.3
 },
 {
  "partNo": "EKMW401VSN221MQ25S",
  "weight": 22.85
 },
 {
  "partNo": "EKMW401VSN331MQ35S",
  "weight": 31.35
 },
 {
  "partNo": "EKMW401VSN391MQ40S",
  "weight": 36.05
 },
 {
  "partNo": "EKMW451VSN561MR50S",
  "weight": 62
 },
 {
  "partNo": "EKRE160ETC470MF05D",
  "weight": 0.51
 },
 {
  "partNo": "EKRG100ELL222MK15S",
  "weight": 3.1
 },
 {
  "partNo": "EKXG161ELL680MK20S",
  "weight": 3.9
 },
 {
  "partNo": "EKXG201ETD330MJ20S",
  "weight": 2.625
 },
 {
  "partNo": "EKXG251ELL220MJ20S",
  "weight": 2.56
 },
 {
  "partNo": "EKXG251ELL221MMN3S",
  "weight": 13.32
 },
 {
  "partNo": "EKXG251ELL470MK20S",
  "weight": 4.03
 },
 {
  "partNo": "EKXG401ELL121MMP1S",
  "weight": 14.44
 },
 {
  "partNo": "EKXG401ELL6R8MJ16S",
  "weight": 2
 },
 {
  "partNo": "EKXG401ELL820MM25S",
  "weight": 10.96
 },
 {
  "partNo": "EKXG401ETD330ML20S",
  "weight": 6.8
 },
 {
  "partNo": "EKXG401ETD470MM20S",
  "weight": 8.84
 },
 {
  "partNo": "EKXG401ETD820MM25S",
  "weight": 11.08
 },
 {
  "partNo": "EKXG451ELL101MM40S",
  "weight": 16.68
 },
 {
  "partNo": "EKXG451ELL6R8MJ20S",
  "weight": 2.56
 },
 {
  "partNo": "EKXJ161ELL101MK20S",
  "weight": 4.25
 },
 {
  "partNo": "EKXJ161ETD181MK30S-R",
  "weight": 6.6
 },
 {
  "partNo": "EKXJ201EC3470MJ20S",
  "weight": 2.675
 },
 {
  "partNo": "EKXJ201ELL101MU20S",
  "weight": 5.98
 },
 {
  "partNo": "EKXJ201ELL181MM20S",
  "weight": 9.08
 },
 {
  "partNo": "EKXJ201ELL331ML40S",
  "weight": 13.76
 },
 {
  "partNo": "EKXJ251ELL181MM25S",
  "weight": 10.9
 },
 {
  "partNo": "EKXJ251ELL271ML40S",
  "weight": 14.44
 },
 {
  "partNo": "EKXJ351EBD680MK35S",
  "weight": 7
 },
 {
  "partNo": "EKXJ351ELL220MJ20S",
  "weight": 2.82
 },
 {
  "partNo": "EKXJ351ELL470MK25S",
  "weight": 5.28
 },
 {
  "partNo": "EKXJ351ELL680MK35S",
  "weight": 7.34
 },
 {
  "partNo": "EKXJ401EC3101MLP1S",
  "weight": 12.56
 },
 {
  "partNo": "EKXJ401ELL181MM45S",
  "weight": 18.4
 },
 {
  "partNo": "EKXJ401ELL220MJ25S",
  "weight": 3.5
 },
 {
  "partNo": "EKXJ401ELL270MK20S",
  "weight": 4.35
 },
 {
  "partNo": "EKXJ401ELL470MK30S",
  "weight": 6.2
 },
 {
  "partNo": "EKXJ401ELL470ML20S",
  "weight": 7.4
 },
 {
  "partNo": "EKXJ401ELL680ML25S",
  "weight": 8.8
 },
 {
  "partNo": "EKXJ401ETD100MJ16S",
  "weight": 2.2625
 },
 {
  "partNo": "EKXJ401ETD470ML20S",
  "weight": 7.76
 },
 {
  "partNo": "EKXJ421ELL680MLN3S",
  "weight": 10.22
 },
 {
  "partNo": "EKXJ421ELL820MMN3S",
  "weight": 13.08
 },
 {
  "partNo": "EKXJ451ELL470ML25S",
  "weight": 8.78
 },
 {
  "partNo": "EKXL421EC3121MM30S",
  "weight": 15.26
 },
 {
  "partNo": "EKXL451ELL560MM20S",
  "weight": 9.4
 },
 {
  "partNo": "EKXQ421ELL910MLN3S",
  "weight": 11.28
 },
 {
  "partNo": "EKY-100ELL101ME11D",
  "weight": 0.53
 },
 {
  "partNo": "EKY-100ELL222MJ30S",
  "weight": 3.4
 },
 {
  "partNo": "EKY-100ETD221MF11D",
  "weight": 0.81
 },
 {
  "partNo": "EKY-101EC3101MJ20S",
  "weight": 2.86
 },
 {
  "partNo": "EKY-101ETD270MHB5D",
  "weight": 1.36
 },
 {
  "partNo": "EKY-101ETD6R8ME11D",
  "weight": 0.635
 },
 {
  "partNo": "EKY-160ELL102MJ20S",
  "weight": 2.475
 },
 {
  "partNo": "EKY-160ELL471MJC5S",
  "weight": 1.75
 },
 {
  "partNo": "EKY-160ETD102MJ20S",
  "weight": 2.625
 },
 {
  "partNo": "EKY-160ETD331MHB5D",
  "weight": 1.34
 },
 {
  "partNo": "EKY-250EC5222MM20S",
  "weight": 8
 },
 {
  "partNo": "EKY-250ELL221MHB5D",
  "weight": 1.19
 },
 {
  "partNo": "EKY-250ELL272ML25S",
  "weight": 7.98
 },
 {
  "partNo": "EKY-250ELL332MLN3S",
  "weight": 9.8
 },
 {
  "partNo": "EKY-250ELL470ME11D",
  "weight": 0.5
 },
 {
  "partNo": "EKY-250ELL471MH20D",
  "weight": 1.8
 },
 {
  "partNo": "EKY-250ETC101MF11D",
  "weight": 0.82
 },
 {
  "partNo": "EKY-250ETC331MH15D",
  "weight": 1.5
 },
 {
  "partNo": "EKY-250ETD101MF11D",
  "weight": 0.83
 },
 {
  "partNo": "EKY-250ETD470ME11D",
  "weight": 0.61
 },
 {
  "partNo": "EKY-350ELL151MHB5D",
  "weight": 1.24
 },
 {
  "partNo": "EKY-350ELL222MLN3S",
  "weight": 9.2
 },
 {
  "partNo": "EKY-350ELL471MJ20S",
  "weight": 2.51
 },
 {
  "partNo": "EKY-350ETD330ME11D",
  "weight": 0.615
 },
 {
  "partNo": "EKY-500EC5100ME11D",
  "weight": 0.4
 },
 {
  "partNo": "EKY-500ELL102MK40S",
  "weight": 7.6
 },
 {
  "partNo": "EKY-500ELL330MF11D",
  "weight": 0.7
 },
 {
  "partNo": "EKY-500ELL471MK20S",
  "weight": 4.05
 },
 {
  "partNo": "EKY-500ELL681MK30S",
  "weight": 5.77
 },
 {
  "partNo": "EKY-500ETD221MJ16S",
  "weight": 2.25
 },
 {
  "partNo": "EKY-630ETD271MK20S",
  "weight": 4.36
 },
 {
  "partNo": "EKY-630ETD471MK30S",
  "weight": 5.88
 },
 {
  "partNo": "EKY-800ELL101MJ16S",
  "weight": 2.24
 },
 {
  "partNo": "EKY-800ELL471ML25S",
  "weight": 8.12
 },
 {
  "partNo": "EKYA350ELL221MHB5D",
  "weight": 1.22
 },
 {
  "partNo": "EKYA350ETC101MF11D",
  "weight": 0.82
 },
 {
  "partNo": "EKYA350ETD101MF11D",
  "weight": 0.84
 },
 {
  "partNo": "EKYA350ETD330ME11D",
  "weight": 0.615
 },
 {
  "partNo": "EKYA350ETD470ME11D",
  "weight": 0.62
 },
 {
  "partNo": "EKYA500ELL1R0ME11D",
  "weight": 0.45
 },
 {
  "partNo": "EKYA500ELL470MF11D",
  "weight": 0.75
 },
 {
  "partNo": "EKYA500ELL821MK25S",
  "weight": 5.26
 },
 {
  "partNo": "EKYA500ETC470MF11D",
  "weight": 0.83
 },
 {
  "partNo": "EKYA500ETD220ME11D",
  "weight": 0.62
 },
 {
  "partNo": "EKYA500ETD470MF11D",
  "weight": 0.82
 },
 {
  "partNo": "EKYA630ETD150ME11D",
  "weight": 0.63
 },
 {
  "partNo": "EKYA630ETD330MF11D",
  "weight": 0.815
 },
 {
  "partNo": "EKYB101ELL221MK25S",
  "weight": 5
 },
 {
  "partNo": "EKYB101ELL331ML25S",
  "weight": 8.22
 },
 {
  "partNo": "EKYB101ELL561MM25S",
  "weight": 10.74
 },
 {
  "partNo": "EKYB250ELL822MMP1S",
  "weight": 15
 },
 {
  "partNo": "EKYB350ELL222MM20S",
  "weight": 8.7
 },
 {
  "partNo": "EKYB350ELL821MJ25S",
  "weight": 3.33
 },
 {
  "partNo": "EKYB500ELL101MHB5D",
  "weight": 1.26
 },
 {
  "partNo": "EKYB500ETD560MF11D",
  "weight": 0.84
 },
 {
  "partNo": "EKYB630ELL121MJC5S",
  "weight": 1.84
 },
 {
  "partNo": "EKYB630ELL681ML20S",
  "weight": 6.92
 },
 {
  "partNo": "EKYB630ETD181MJ16S",
  "weight": 2.35
 },
 {
  "partNo": "EKYB800ELL152MMP1S",
  "weight": 16.04
 },
 {
  "partNo": "EKZE100ETD101ME11D",
  "weight": 0.625
 },
 {
  "partNo": "EKZE100ETD221MF11D",
  "weight": 0.825
 },
 {
  "partNo": "EKZE101ELL101MK16S",
  "weight": 3.45
 },
 {
  "partNo": "EKZE160ELL102MJ20S",
  "weight": 2.425
 },
 {
  "partNo": "EKZE160ELL332MK35S",
  "weight": 7.1
 },
 {
  "partNo": "EKZE160ELL471MHB5D",
  "weight": 1.22
 },
 {
  "partNo": "EKZE250ELL152MK25S",
  "weight": 5
 },
 {
  "partNo": "EKZE250ELL470ME11D",
  "weight": 0.523333
 },
 {
  "partNo": "EKZE250ELL471MH20D",
  "weight": 1.65
 },
 {
  "partNo": "EKZE250ELL681MJ20S",
  "weight": 2.625
 },
 {
  "partNo": "EKZE250ETD101MF11D",
  "weight": 0.805
 },
 {
  "partNo": "EKZE250ETD331MH15D",
  "weight": 1.58
 },
 {
  "partNo": "EKZE350ELL122ML20S",
  "weight": 6.4
 },
 {
  "partNo": "EKZE350ETD331MJ16S",
  "weight": 2.3375
 },
 {
  "partNo": "EKZE350ETD471MJ20S",
  "weight": 2.6875
 },
 {
  "partNo": "EKZE500ELL220ME11D",
  "weight": 0.53
 },
 {
  "partNo": "EKZE500ELL221MJ16S",
  "weight": 2.18
 },
 {
  "partNo": "EKZE500ELL681MK30S",
  "weight": 5.55
 },
 {
  "partNo": "EKZE500ETD221MJ16S",
  "weight": 2.3
 },
 {
  "partNo": "EKZE800ELL391MK30S",
  "weight": 5.98
 },
 {
  "partNo": "EKZH100ELL102MJC5S",
  "weight": 1.81
 },
 {
  "partNo": "EKZH160ELL182MJ25S",
  "weight": 3.33
 },
 {
  "partNo": "EKZH160ELL221MF11D",
  "weight": 0.73
 },
 {
  "partNo": "EKZH160ELL681MJC5S",
  "weight": 1.875
 },
 {
  "partNo": "EKZH160ETD102MJ16S",
  "weight": 2.3625
 },
 {
  "partNo": "EKZH250ELL102MJ25S",
  "weight": 3.2
 },
 {
  "partNo": "EKZH250ELL152MK20S",
  "weight": 4.36
 },
 {
  "partNo": "EKZH350ELL101MF11D",
  "weight": 0.75
 },
 {
  "partNo": "EKZH350ELL102MK20S",
  "weight": 4
 },
 {
  "partNo": "EKZH350ELL152MK30S",
  "weight": 5.84
 },
 {
  "partNo": "EKZH350ELL221MHB5D",
  "weight": 1.15
 },
 {
  "partNo": "EKZH350ELL331MJC5S",
  "weight": 1.865
 },
 {
  "partNo": "EKZH350ELL470ME11D",
  "weight": 0.52
 },
 {
  "partNo": "EKZH350ELL471MJ16S",
  "weight": 2.22
 },
 {
  "partNo": "EKZH350ETD331MJC5S",
  "weight": 1.95
 },
 {
  "partNo": "EKZH6R3ELL152MH20D",
  "weight": 1.8
 },
 {
  "partNo": "EKZH6R3ELL182MJ16S",
  "weight": 2.25
 },
 {
  "partNo": "EKZH6R3ELL471MF11D",
  "weight": 0.75
 },
 {
  "partNo": "EKZM100ELL102MJC5S",
  "weight": 1.84
 },
 {
  "partNo": "EKZM160ELL152MJ20S",
  "weight": 2.695
 },
 {
  "partNo": "EKZM160ELL221MF11D",
  "weight": 0.7
 },
 {
  "partNo": "EKZM350ELL681MJ25S",
  "weight": 3.34
 },
 {
  "partNo": "EKZN100EC3122MJ16S",
  "weight": 2.366667
 },
 {
  "partNo": "EKZN100ELL102MJC5S",
  "weight": 1.85
 },
 {
  "partNo": "EKZN101EC3271MK30S-R",
  "weight": 6.46
 },
 {
  "partNo": "EKZN160ELL332MK251",
  "weight": 6.72
 },
 {
  "partNo": "EKZN160ELL392MK35S",
  "weight": 7
 },
 {
  "partNo": "EKZN160ETD102MJ16S",
  "weight": 2.25
 },
 {
  "partNo": "EKZN160ETD332MK251",
  "weight": 5.44
 },
 {
  "partNo": "EKZN250ELL222MK30S",
  "weight": 5.5
 },
 {
  "partNo": "EKZN250ELL272MK35S",
  "weight": 7.1
 },
 {
  "partNo": "EKZN350EC3182MK35S",
  "weight": 7.4
 },
 {
  "partNo": "EKZN350EC3681MJ25S",
  "weight": 3.48
 },
 {
  "partNo": "EKZN350ELL182MK35S",
  "weight": 7.12
 },
 {
  "partNo": "EKZN500ELL391MJ25S",
  "weight": 3.4
 },
 {
  "partNo": "EKZN630ETD681MK30S-R",
  "weight": 6.2
 },
 {
  "partNo": "EKZN6R3ELL471MF11D",
  "weight": 0.65
 },
 {
  "partNo": "EKZN800ELL681ML25S",
  "weight": 8.9
 },
 {
  "partNo": "EKZN800ELL820MJC5S",
  "weight": 1.9
 },
 {
  "partNo": "ELE-500ELL4R7ME11D",
  "weight": 0.53
 },
 {
  "partNo": "ELXM201VSN681MQ40S",
  "weight": 30.35
 },
 {
  "partNo": "ELXM401VSN331MA35S",
  "weight": 47.75
 },
 {
  "partNo": "ELXQ451VSN820MP25S",
  "weight": 16.2
 },
 {
  "partNo": "ELXS201VSN122MQ45S",
  "weight": 41.15
 },
 {
  "partNo": "ELXS3B1VSN102MA45S",
  "weight": 74
 },
 {
  "partNo": "ELXS3B1VSN221MQ25S",
  "weight": 21.7
 },
 {
  "partNo": "ELXS421VSN121KQ25S",
  "weight": 21.05
 },
 {
  "partNo": "ELXS451VSN221MR30S",
  "weight": 34.9
 },
 {
  "partNo": "ELXS501VSN471MA60S",
  "weight": 80
 },
 {
  "partNo": "ELXV101ELL120MFB5D",
  "weight": 0.7
 },
 {
  "partNo": "ELXV160EMC122MJ30S",
  "weight": 3.45
 },
 {
  "partNo": "ELXV160ETD122MJ30S",
  "weight": 3.6
 },
 {
  "partNo": "ELXV500ETD221MJ25S",
  "weight": 3.0375
 },
 {
  "partNo": "ELXY250ELL182ML25S",
  "weight": 7.6
 },
 {
  "partNo": "ELXY250ELL331MJ16S",
  "weight": 1.98
 },
 {
  "partNo": "ELXY250ELL561MJ25S",
  "weight": 3.05
 },
 {
  "partNo": "ELXY250ETD121MF15D",
  "weight": 0.975
 },
 {
  "partNo": "ELXY350EC3221MH20D",
  "weight": 1.61
 },
 {
  "partNo": "ELXY350ELL102MK30S",
  "weight": 5.6
 },
 {
  "partNo": "ELXY350ETD331MJ20S",
  "weight": 2.675
 },
 {
  "partNo": "ELXY500EC3681MK35S",
  "weight": 7.12
 },
 {
  "partNo": "ELXY500EC3820MH15D",
  "weight": 1.3
 },
 {
  "partNo": "ELXY500ELL471MK25S",
  "weight": 4.75
 },
 {
  "partNo": "ELXY500ELL821ML25S",
  "weight": 7.4
 },
 {
  "partNo": "ELXY630ELL471ML25S",
  "weight": 7.08
 },
 {
  "partNo": "ELXY630ELL560MJC5S",
  "weight": 1.73
 },
 {
  "partNo": "ELXZ100ETC331MF15D",
  "weight": 1
 },
 {
  "partNo": "ELXZ160EC3221MF15S",
  "weight": 0.86
 },
 {
  "partNo": "ELXZ250EC3271MH15D",
  "weight": 1.25
 },
 {
  "partNo": "ELXZ250EC3332MM25S",
  "weight": 9.72
 },
 {
  "partNo": "ELXZ250ELL221MH12D",
  "weight": 1.22
 },
 {
  "partNo": "ELXZ250ELL272ML25S",
  "weight": 7.8
 },
 {
  "partNo": "ELXZ250ELL472MM35S",
  "weight": 11.4
 },
 {
  "partNo": "ELXZ250ETC101MFB5D",
  "weight": 0.82
 },
 {
  "partNo": "ELXZ250ETC331MH15D",
  "weight": 1.52
 },
 {
  "partNo": "ELXZ250ETD102MJ30S",
  "weight": 3.66
 },
 {
  "partNo": "ELXZ350EC3331MJ16S",
  "weight": 2
 },
 {
  "partNo": "ELXZ350ELL151MH12D",
  "weight": 1.23
 },
 {
  "partNo": "ELXZ350ETD471MJ20S",
  "weight": 2.575
 },
 {
  "partNo": "ELXZ500ELL121MH15D",
  "weight": 1.48
 },
 {
  "partNo": "ELXZ500ELL182ML40S",
  "weight": 12.32
 },
 {
  "partNo": "ELXZ630ELL821ML30S",
  "weight": 8.02
 },
 {
  "partNo": "ELXZ6R3ETD152MJ20S",
  "weight": 2.825
 },
 {
  "partNo": "EMHS101GRA151MKG5S",
  "weight": 5.2
 },
 {
  "partNo": "EMLF250ARA101MHA0G",
  "weight": 1.56
 },
 {
  "partNo": "EMVA100ARA101MF55G",
  "weight": 0.7
 },
 {
  "partNo": "EMVA160ADA101MF55G",
  "weight": 0.51
 },
 {
  "partNo": "EMVA160ADA470ME55G",
  "weight": 0.38
 },
 {
  "partNo": "EMVA250ADA330ME55G",
  "weight": 0.38
 },
 {
  "partNo": "EMVA250ADA331MHA0G",
  "weight": 1.36
 },
 {
  "partNo": "EMVA250ARA101MF80G",
  "weight": 0.888889
 },
 {
  "partNo": "EMVA350ADA331MJA0G",
  "weight": 1.84
 },
 {
  "partNo": "EMVA350ARA151MHA0G",
  "weight": 1.52
 },
 {
  "partNo": "EMVA350ARA470MF60G",
  "weight": 0.68
 },
 {
  "partNo": "EMVA500ADA102MLN0S",
  "weight": 8.16
 },
 {
  "partNo": "EMVA500ARA101MHA0G",
  "weight": 1.6
 },
 {
  "partNo": "EMVA500ARA470MF80G",
  "weight": 0.76
 },
 {
  "partNo": "EMVA500ARA471MKG5S",
  "weight": 4.6
 },
 {
  "partNo": "EMVA630ADA100MF55G",
  "weight": 0.52
 },
 {
  "partNo": "EMVA630ADA220MF80G",
  "weight": 0.688889
 },
 {
  "partNo": "EMVA630ADA4R7ME55G",
  "weight": 0.38
 },
 {
  "partNo": "EMVA630ARA1R0MD55G",
  "weight": 0.275
 },
 {
  "partNo": "EMVA630ARA2R2MD55G",
  "weight": 0.28
 },
 {
  "partNo": "EMVA630ARA331MKG5S",
  "weight": 4.75
 },
 {
  "partNo": "EMVA6R3ADA101ME55G",
  "weight": 0.38
 },
 {
  "partNo": "EMVE101ARA330MJA0G",
  "weight": 1.96
 },
 {
  "partNo": "EMVE160ADA101MF55G",
  "weight": 0.52
 },
 {
  "partNo": "EMVE160ARA100MD55G",
  "weight": 0.28
 },
 {
  "partNo": "EMVE160ARA101MF55G",
  "weight": 0.62
 },
 {
  "partNo": "EMVE350ADA100ME55G",
  "weight": 0.38
 },
 {
  "partNo": "EMVE350ADA101MF80G",
  "weight": 0.688889
 },
 {
  "partNo": "EMVE350ARA100ME55G",
  "weight": 0.46
 },
 {
  "partNo": "EMVE500ADA101MHA0G",
  "weight": 1.4
 },
 {
  "partNo": "EMVE500ADA220MF60G",
  "weight": 0.54
 },
 {
  "partNo": "EMVE630ADA101MJA0G",
  "weight": 1.8
 },
 {
  "partNo": "EMVE630ADA1R0MD55G",
  "weight": 0.25
 },
 {
  "partNo": "EMVE630ARA101MJA0G",
  "weight": 2.08
 },
 {
  "partNo": "EMVE6R3ARA101MF55G",
  "weight": 0.68
 },
 {
  "partNo": "EMVH250ADA221MHA0G",
  "weight": 1.38
 },
 {
  "partNo": "EMVH500ARA220MF80G",
  "weight": 0.777778
 },
 {
  "partNo": "EMVK160ADA100MD55G",
  "weight": 0.23
 },
 {
  "partNo": "EMVL500ADA470MHA0G",
  "weight": 1.36
 },
 {
  "partNo": "EMVY101ARA101MKE0S",
  "weight": 4.2
 },
 {
  "partNo": "EMVY160ADA100MD55G",
  "weight": 0.23
 },
 {
  "partNo": "EMVY160ARA471MHA0G",
  "weight": 1.56
 },
 {
  "partNo": "EMVY250ADA101MF80G",
  "weight": 0.666667
 },
 {
  "partNo": "EMVY250ADA331MHA0G",
  "weight": 1.4
 },
 {
  "partNo": "EMVY250ADA470MF55G",
  "weight": 0.52
 },
 {
  "partNo": "EMVY250ARA101MF80G",
  "weight": 0.84
 },
 {
  "partNo": "EMVY250ARA470MF55G",
  "weight": 0.6
 },
 {
  "partNo": "EMVY350ADA220MF55G",
  "weight": 0.51
 },
 {
  "partNo": "EMVY350ADA680MF80G",
  "weight": 0.666667
 },
 {
  "partNo": "EMVY500ADA1R0MD55G",
  "weight": 0.225
 },
 {
  "partNo": "EMVY500ADA2R2MD55G",
  "weight": 0.24
 },
 {
  "partNo": "EMVY630ARA101MKE0S",
  "weight": 3.92
 },
 {
  "partNo": "EMZA100ADA330MD61G",
  "weight": 0.255
 },
 {
  "partNo": "EMZA100ARA330MD61G",
  "weight": 0.305
 },
 {
  "partNo": "EMZA160ADA101MF61G",
  "weight": 0.58
 },
 {
  "partNo": "EMZA160ADA221MF80G",
  "weight": 0.688889
 },
 {
  "partNo": "EMZA160ADA471MHA0G",
  "weight": 1.34
 },
 {
  "partNo": "EMZA160ARA101MF61G",
  "weight": 0.66
 },
 {
  "partNo": "EMZA160ARA221MF80G",
  "weight": 0.766667
 },
 {
  "partNo": "EMZA160ARA470ME61G",
  "weight": 0.5
 },
 {
  "partNo": "EMZA250ADA221MHA0G",
  "weight": 1.36
 },
 {
  "partNo": "EMZA250ARA470MF61G",
  "weight": 0.66
 },
 {
  "partNo": "EMZA500ADA221MJA0G",
  "weight": 1.8
 },
 {
  "partNo": "EMZA500ADA470MF80G",
  "weight": 0.68
 },
 {
  "partNo": "EMZA500ARA221MJA0G",
  "weight": 2
 },
 {
  "partNo": "EMZA500ARA470MF80G",
  "weight": 0.84
 },
 {
  "partNo": "EMZA630ADA330MHA0G",
  "weight": 1.34
 },
 {
  "partNo": "EMZA630ARA330MHA0G",
  "weight": 1.5
 },
 {
  "partNo": "EMZA800ADA100MF80G",
  "weight": 0.666667
 },
 {
  "partNo": "EMZA800ARA100MF80G",
  "weight": 0.766667
 },
 {
  "partNo": "EMZJ160ADA221MF80G",
  "weight": 0.688889
 },
 {
  "partNo": "EMZJ160ARA221MF80G",
  "weight": 0.84
 },
 {
  "partNo": "EMZR250ARA221MF80G",
  "weight": 0.8
 },
 {
  "partNo": "EMZR250ARA680ME61G",
  "weight": 0.51
 },
 {
  "partNo": "EMZR500ARA101MF80G",
  "weight": 0.88
 },
 {
  "partNo": "EMZR500ARA331MJA0G",
  "weight": 2.1
 },
 {
  "partNo": "EPAG401ELL101ML30S",
  "weight": 10.68
 },
 {
  "partNo": "EPH-331ELL800C537S",
  "weight": 6.08
 },
 {
  "partNo": "ESMG100ELL472MK25S",
  "weight": 5.1
 },
 {
  "partNo": "ESMG160ETC471MHB5D",
  "weight": 1.33
 },
 {
  "partNo": "ESMG250ELL332MM20S",
  "weight": 8.56
 },
 {
  "partNo": "ESMG250ETC101MF11D",
  "weight": 0.77
 },
 {
  "partNo": "ESMG250ETC221MHB5D",
  "weight": 1.26
 },
 {
  "partNo": "ESMG250ETC470ME11D",
  "weight": 0.625
 },
 {
  "partNo": "ESMG250ETD102MJ20S",
  "weight": 2.625
 },
 {
  "partNo": "ESMG500ETC101MHB5D",
  "weight": 1.29
 },
 {
  "partNo": "ESMG500ETC1R0ME11D",
  "weight": 0.615
 },
 {
  "partNo": "ESMG500ETC2R2ME11D",
  "weight": 0.58
 },
 {
  "partNo": "ESMG500ETC4R7ME11D",
  "weight": 0.58
 },
 {
  "partNo": "ESMG500ETCR47ME11D",
  "weight": 0.585
 },
 {
  "partNo": "ESMG630ELL221MJ16S",
  "weight": 2.155
 },
 {
  "partNo": "ESMG630ELL471MK20S",
  "weight": 4.14
 },
 {
  "partNo": "ESMM201VSN471MP30S",
  "weight": 16
 },
 {
  "partNo": "ESMQ401VSN681MA40S",
  "weight": 65.2
 },
 {
  "partNo": "ESMQ401VSN821MA45S",
  "weight": 79.15
 },
 {
  "partNo": "ESRA160ELL101MF07D",
  "weight": 0.52
 },
 {
  "partNo": "ESRA250ETC100MD07D",
  "weight": 0.345
 },
 {
  "partNo": "ESRA350ETC100ME07D",
  "weight": 0.435
 },
 {
  "partNo": "ESRA630ELL100MF07D",
  "weight": 0.5
 },
 {
  "partNo": "ESRM160ETC100MD05D",
  "weight": 0.32
 },
 {
  "partNo": "EUFL501VNN122VB90U",
  "weight": 176
 },
 {
  "partNo": "HHXA500ARA330MF80G",
  "weight": 0.755556
 },
 {
  "partNo": "HHXB250ARA101MF80G",
  "weight": 0.755556
 },
 {
  "partNo": "HHXB630ARA220MF80G",
  "weight": 0.766667
 },
 {
  "partNo": "HHXC350ARA470MF61G",
  "weight": 0.66
 },
 {
  "partNo": "HHXC500ARA330MF80G",
  "weight": 0.744444
 },
 {
  "partNo": "HHXD500ARA220MF61G",
  "weight": 0.66
 },
 {
  "partNo": "HHXJ350ARA331MJA0G",
  "weight": 1.96
 },
 {
  "partNo": "KTD101B474M32A0B00",
  "weight": 0.23
 },
 {
  "partNo": "KTS101B335M55N0T00",
  "weight": 0.4375
 },
 {
  "partNo": "KTS101B475M43E0T00",
  "weight": 0.3
 },
 {
  "partNo": "KTS101B685M55F0T00",
  "weight": 0.5125
 },
 {
  "partNo": "TND05V-390KTBAAAA0",
  "weight": 0.62
 },
 {
  "partNo": "TND07V-201KTFAAAA0",
  "weight": 0.7
 },
 {
  "partNo": "TND07V-471KB00AAA0",
  "weight": 0.83
 },
 {
  "partNo": "TND09V-121KB00AAA0",
  "weight": 1
 },
 {
  "partNo": "TND10SV681KTLBPAA0",
  "weight": 2.66
 },
 {
  "partNo": "TND10V-122KB00AAA0",
  "weight": 3.3
 },
 {
  "partNo": "TND10V-330KB00AAA0",
  "weight": 1.2
 },
 {
  "partNo": "TND10V-471KB00AAA0",
  "weight": 1.6
 },
 {
  "partNo": "TND10V-681KB00AAA0",
  "weight": 2.1
 },
 {
  "partNo": "TND14V-221KB00AAA0",
  "weight": 1.6
 },
 {
  "partNo": "TND14V-471KB00AAA0",
  "weight": 2.91
 },
 {
  "partNo": "TND14V-681KB00AAA0",
  "weight": 3.53
 },
 {
  "partNo": "TND15GF471KB00EAA0",
  "weight": 3.45
 },
 {
  "partNo": "EXS00A-CG05881",
  "weight": 0.306667
 },
 {
  "partNo": "EXS00A-CG05989",
  "weight": 0.14
 },
 {
  "partNo": "EXS00A-CG06475",
  "weight": 0.04
 },
 {
  "partNo": "NX2520SA-32.000M-STD-CSW-2",
  "weight": 0.033333
 },
 {
  "partNo": "NX3215SA-32.768K-EXS00A-MU00525",
  "weight": 0.046667
 },
 {
  "partNo": "NX3215SA-32.768K-STD-MUA-14",
  "weight": 0.043333
 },
 {
  "partNo": "NX3215SA-32.768K-STD-MUA-8",
  "weight": 0.046
 },
 {
  "partNo": "NX3225GA-12.000M-STD-CRG-2",
  "weight": 0.04
 },
 {
  "partNo": "NX3225GA-13.560M-STD-CRG-2",
  "weight": 0.04
 },
 {
  "partNo": "NX3225GA-14.7456M-STD-CRG-2",
  "weight": 0.05
 },
 {
  "partNo": "NX3225GA-16.000M-STD-CRG-2",
  "weight": 0.05
 },
 {
  "partNo": "NX3225GA-25.000M-STD-CRG-2",
  "weight": 0.04
 },
 {
  "partNo": "NX3225GD-8.000M-EXS00A-CG04874",
  "weight": 0.046667
 },
 {
  "partNo": "NX5032GA-48.000M-STD-CSK-8",
  "weight": 0.14
 },
 {
  "partNo": "NX8045GB-20.000M-STD-CSF-4",
  "weight": 0.28
 },
 {
  "partNo": "NX8045GB-8.000M-STD-CSF-4",
  "weight": 0.28
 },
 {
  "partNo": "CFS-0801MB",
  "weight": 1.75
 },
 {
  "partNo": "CFS-0802TA",
  "weight": 1.4375
 },
 {
  "partNo": "CHS-02B2",
  "weight": 0.072
 },
 {
  "partNo": "CJS-1200TB",
  "weight": 0.25
 },
 {
  "partNo": "CJS-1200TB1",
  "weight": 0.2
 },
 {
  "partNo": "CJS-1200TB2",
  "weight": 0.22
 },
 {
  "partNo": "CSS-1210TB",
  "weight": 0.29
 },
 {
  "partNo": "S-2050",
  "weight": 0.5
 },
 {
  "partNo": "ST-32ETB55",
  "weight": 0.2
 },
 {
  "partNo": "FPB22W224K",
  "weight": 0.6
 },
 {
  "partNo": "FPB22W334K",
  "weight": 0.7
 },
 {
  "partNo": "FPB22W474K",
  "weight": 0.8
 },
 {
  "partNo": "FPB22W684K",
  "weight": 1.15
 },
 {
  "partNo": "FPD22W225K4",
  "weight": 8.4
 },
 {
  "partNo": "FPS22W105K4P15R",
  "weight": 1
 },
 {
  "partNo": "FPS22W225K4R",
  "weight": 2.2
 },
 {
  "partNo": "FPT22J105K2",
  "weight": 3
 },
 {
  "partNo": "MDS22G104K",
  "weight": 0.8
 },
 {
  "partNo": "MDS22G154K",
  "weight": 0.9
 },
 {
  "partNo": "MDS22J223K-F5T",
  "weight": 0.9
 },
 {
  "partNo": "MDX22W155K-F",
  "weight": 3
 },
 {
  "partNo": "EKZE350ELL681MK20S",
  "weight": 4.05
 },
 {
  "partNo": "TND07V-220KB00AAA0",
  "weight": 0.58
 },
 {
  "partNo": "T9AS1D14-12",
  "weight": 30
 },
 {
  "partNo": "AFC450V105K",
  "weight": 3.4
 },
 {
  "partNo": "AFC450V474K",
  "weight": 2
 },
 {
  "partNo": "LE103",
  "weight": 0.75
 },
 {
  "partNo": "LE104-FX3111",
  "weight": 1.15
 },
 {
  "partNo": "LE105-FX4111",
  "weight": 4.8
 },
 {
  "partNo": "LE155-FX5211",
  "weight": 8.4
 },
 {
  "partNo": "LE224-FX3111",
  "weight": 1.75
 },
 {
  "partNo": "LE225-MX",
  "weight": 13.2
 },
 {
  "partNo": "LE334-FX3231",
  "weight": 2.25
 },
 {
  "partNo": "LE474-FX3211",
  "weight": 2.8
 },
 {
  "partNo": "LE684-FX4231",
  "weight": 3.695
 },
 {
  "partNo": "PA103-LK",
  "weight": 1.4
 },
 {
  "partNo": "R26-362-BGL",
  "weight": 0.8
 },
 {
  "partNo": "RA-351P-C6-Y",
  "weight": 0.65
 },
 {
  "partNo": "RE224-L",
  "weight": 3
 },
 {
  "partNo": "RE334-L",
  "weight": 4.4
 },
 {
  "partNo": "RE474-L",
  "weight": 5.5
 },
 {
  "partNo": "RHCA-301Q43U",
  "weight": 0.38
 },
 {
  "partNo": "YF473",
  "weight": 2.8153
 },
 {
  "partNo": "D1N60-5070",
  "weight": 0.166
 },
 {
  "partNo": "DF30SC3ML7072",
  "weight": 1.85
 },
 {
  "partNo": "D10XB60-7000",
  "weight": 4.8
 },
 {
  "partNo": "D1FL20U-5053",
  "weight": 0.1
 },
 {
  "partNo": "D1FL40U-5053",
  "weight": 0.1
 },
 {
  "partNo": "D1FS6-5053",
  "weight": 0.1
 },
 {
  "partNo": "D1N60-5060",
  "weight": 0.225
 },
 {
  "partNo": "M1F60-6063*J4",
  "weight": 0.06
 },
 {
  "partNo": "S20LC40UT-5000",
  "weight": 5.4
 },
 {
  "partNo": "S30SC4MT-5000",
  "weight": 5.4
 },
 {
  "partNo": "S3L60-5000",
  "weight": 1
 },
 {
  "partNo": "S60SC4MT-5000",
  "weight": 5.52
 },
 {
  "partNo": "SF10L60U-7600",
  "weight": 2
 },
 {
  "partNo": "SC-20S(20PPM/12.5PF)",
  "weight": 0.026667
 },
 {
  "partNo": "SC-20S(20PPM/6PF)",
  "weight": 0.033333
 },
 {
  "partNo": "SSP-T7-F(20PPM/7PF)",
  "weight": 0.06
 },
 {
  "partNo": "2-2176051-9",
  "weight": 0.06
 },
 {
  "partNo": "AMP(1-770166-0)",
  "weight": 0.85
 },
 {
  "partNo": "AMP(1-770174-0)",
  "weight": 1.4
 },
 {
  "partNo": "AMP(1-770178-0)",
  "weight": 1.9
 },
 {
  "partNo": "AMP(2232905-1)",
  "weight": 0.1625
 },
 {
  "partNo": "AMP(292133-2)",
  "weight": 0.15
 },
 {
  "partNo": "AMP(5-103634-4)",
  "weight": 1.7
 },
 {
  "partNo": "AMP(5-5530843-0)",
  "weight": 8.6
 },
 {
  "partNo": "AMP(640385-8)",
  "weight": 2.46
 },
 {
  "partNo": "AMP(796634-3)",
  "weight": 5.5
 },
 {
  "partNo": "PJS008U-3000-0",
  "weight": 1.2
 },
 {
  "partNo": "CN113-230-0001(01)VE",
  "weight": 9
 }
];
