// GENERATED by scripts/gen-seed-real-data.mjs — do not edit by hand.
// Source: new_seed/ORIGINAL_ID + ORG_ID + Sub Inventory mapping.xlsx (Enable Subinv Data).
// Plain (org_id, secondary_inventory_name) groups; sharing between stores is configured per
// warehouse via sub_inventory_share_members.
export const realSubInventories = [
 {
  "orgId": 12,
  "secondaryInventoryName": "BJMD1",
  "subinvDescription": "曼德电子电器有限公司保定徐水光电分公司 （VMI)"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "CHECKING",
  "subinvDescription": "Store For Return And Special Processing"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJZHK",
  "subinvDescription": "Store 1 in SZ Warehouse (Final to HK)"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJSH",
  "subinvDescription": "Store 1 in SH Warehouse From BJ"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJHK2",
  "subinvDescription": "BJ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJCC1",
  "subinvDescription": "Store 1 in Beijing w/o Locator for Chang Chun"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJBJ1",
  "subinvDescription": "Store 1 in Beijing w/o Locator"
 },
 {
  "orgId": 12,
  "secondaryInventoryName": "BJMD2",
  "subinvDescription": "曼德汽车零部件（邳州）有限公司电子分公司 （VMI)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "XFUSION",
  "subinvDescription": "xFusion Digital Technologies in Macau"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "ZTE",
  "subinvDescription": "ZTE in Macau"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "THNE2",
  "subinvDescription": "[过渡仓]经MCE Office？购，发给TH Office"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "HUAWEI",
  "subinvDescription": "Hua Wei Store in Macau (VMI)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store (For COA Data Fix)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "BJHK1",
  "subinvDescription": "(MCE)BJHK1 for BJ office Only (HK Location)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "GZHK1",
  "subinvDescription": "(MCE)GZHK1 for GZ office Only (HK Location)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "SZHK1",
  "subinvDescription": "(MCE)SZHK1 for SZ office Only (HK Location)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Testing for MCE Extenral Office"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging for MCE Extenral Office"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "SHHK1",
  "subinvDescription": "(MCE)SHHK1 for SH office Only (HK Location)"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "MCOHW",
  "subinvDescription": "MCO Hua Wei VMI"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "HWOS",
  "subinvDescription": "Old Stock for HuaWei in Macau"
 },
 {
  "orgId": 140,
  "secondaryInventoryName": "HUAWEI-CAR",
  "subinvDescription": "Hua Wei Car Store in Macau (VMI)"
 },
 {
  "orgId": 143,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store1 for NMCI Intenral Ofiice"
 },
 {
  "orgId": 143,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging for NMCI Intenral Office"
 },
 {
  "orgId": 143,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store (For COA Data Fix)"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "BJHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "BJHK2",
  "subinvDescription": "BJ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "BJSH",
  "subinvDescription": "Store 1 in SH Warehouse From BJ"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "BJSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "CHECKING",
  "subinvDescription": "Store For Return And Special Processing"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "GZGZ1",
  "subinvDescription": "Store 1 in Guangzhou w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "GZHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "GZHK2",
  "subinvDescription": "GZ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "GZSH",
  "subinvDescription": "GZ Store (Location: SH)"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "GZSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "HUAWEI",
  "subinvDescription": "Hua Wei Store in Macau (VMI)"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "HWOS",
  "subinvDescription": "Old Stock for HuaWei in Macau"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "ITSTORE1",
  "subinvDescription": "IT Store1 in Macau"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "MCOHW",
  "subinvDescription": "MCO Hua Wei VMI"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "PRC1",
  "subinvDescription": "PRC1"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SHHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SHHK2",
  "subinvDescription": "SH Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SHSH1",
  "subinvDescription": "Store 1 in Shanghai w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SHSH2",
  "subinvDescription": "Store 2  in Shanghai w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SHSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store 1 in Macau"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SZHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SZHK2",
  "subinvDescription": "SZ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SZPRC1",
  "subinvDescription": "SZPRC1"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SZSH",
  "subinvDescription": "SZ Store (Location: SH)"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "SZSZ1",
  "subinvDescription": "Store 1 in Shenzhen w/o Locator"
 },
 {
  "orgId": 9,
  "secondaryInventoryName": "ZTE",
  "subinvDescription": "ZTE in Macau"
 },
 {
  "orgId": 120,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store1 for MCX Office"
 },
 {
  "orgId": 120,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store (For COA Data Fix)"
 },
 {
  "orgId": 120,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging for MCX Office"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDHF",
  "subinvDescription": "Store in Mei Di (He Fei) (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZZHK",
  "subinvDescription": "Store 1 in SZ Warehouse (Final to HK)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZSH",
  "subinvDescription": "GZ Store (Location: SH)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDWH",
  "subinvDescription": "VMI Store in Mei Di (Wu Hu Mei Zi)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDWA",
  "subinvDescription": "VMI Store in Mei Di (Wu Han)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDNS",
  "subinvDescription": "Store in Mei Di (Nan Sha) (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDJZ",
  "subinvDescription": "Store in Mei Di (Jing zhou) (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDHD",
  "subinvDescription": "Store in Mei Di (Han Dan) (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDCQ",
  "subinvDescription": "VMI Store in Mei Di (Chong Qing)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMDCF",
  "subinvDescription": "Store in Mei Di (Kitchen) (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZMD",
  "subinvDescription": "Store in Mei Di (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZHK2",
  "subinvDescription": "GZ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZGZ1",
  "subinvDescription": "Store 1 in Guangzhou w/o Locator"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "CHECKING",
  "subinvDescription": "Store For Return And Special Processing"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZYZHS",
  "subinvDescription": "扬州华声 (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZGDHS",
  "subinvDescription": "广东华声 (VMI)"
 },
 {
  "orgId": 14,
  "secondaryInventoryName": "GZAHMZ",
  "subinvDescription": "安徽美芝精密 (VMI)"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "ITSTORE1",
  "subinvDescription": "Store 1 in Hong Kong for IT Business"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store 1 in Hong Kong w/o Locator"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "WSTORE1",
  "subinvDescription": "Store 1 in Hong Kong w/o Locator for Wong's"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "ZTE",
  "subinvDescription": "Store 1 in Hong Kong w/o Locator for ZTE"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "GAMSHENG",
  "subinvDescription": "VMI Store for SH GAMSHENG"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 2,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "MEIZHI",
  "subinvDescription": "安徽美芝 VMI"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "HFMD",
  "subinvDescription": "合肥美的 VMI"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "FEILING",
  "subinvDescription": "无锡飞翎 VMI"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "CHECKING",
  "subinvDescription": "Store For Return And Special Processing"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHZHK",
  "subinvDescription": "Store 1 in SZ Warehouse (Final to HK)"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHSH3",
  "subinvDescription": "Store 3 in SH w/o Locator used for SH-JINMAI-01"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "XP(TFREEW)",
  "subinvDescription": "XP POWER Tax Free Warehouse， 上海保税区内的中转仓"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHWH1",
  "subinvDescription": "Store 1 in Shanghai w/o Locator for Wu Han"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHSZ",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHSH2",
  "subinvDescription": "Store 2  in Shanghai w/o Locator"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHLX",
  "subinvDescription": "For 立讯专用, Store in Shanghai w/o Locator"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHFL",
  "subinvDescription": "VMI 无锡飞翎"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHSH1",
  "subinvDescription": "Store 1 in Shanghai w/o Locator"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHQD1",
  "subinvDescription": "Qingdao's Store"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHNJ1",
  "subinvDescription": "Store 1 in Shanghai w/o Locator for Nan Jing"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHHK2",
  "subinvDescription": "SH Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "SHHF1",
  "subinvDescription": "Store 1 in Shanghai w/o Locator for Hefei"
 },
 {
  "orgId": 5,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA965",
  "subinvDescription": "BYDA (电动总成厂) / Code: A965 / 坪山"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA966",
  "subinvDescription": "BYDA (电动汽车研究所) / Code: A966 / 坪山"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDH141",
  "subinvDescription": "BYDA (惠州电源工厂) / Code: H141 / 惠州"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDHZ25",
  "subinvDescription": "VMI BYDA (惠州电源工厂) / Code: H141/ 惠州"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZDAMAGE",
  "subinvDescription": "Store1 in SZ for Keep Damaged Item w/o Locator"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZHK1",
  "subinvDescription": "Store 1 in Hongkong w/o Locator"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZHK2",
  "subinvDescription": "SZ Store (Loc: HK) 货要从香港进口国内"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZSH",
  "subinvDescription": "SZ Store (Location: SH)"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZSZ1",
  "subinvDescription": "Store 1 in Shenzhen w/o Locator"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZVMAX",
  "subinvDescription": "Store in 威迈斯 (VMI)"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZXM1",
  "subinvDescription": "Store 1 in Xiamen w/o Locator"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZZHK",
  "subinvDescription": "Store 1 in SZ Warehouse"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZHW-NOR",
  "subinvDescription": "Hua Wei store in SZ warehouse location"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "CHECKING",
  "subinvDescription": "Store For Return And Special Processing"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "DUMMY",
  "subinvDescription": "Dummy Store"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "ICHAUS",
  "subinvDescription": "普通仓，存储黎小田ICAHUS的备货"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store 1 in Shenzhen w/o Locator"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA860",
  "subinvDescription": "BYDA (汽车工业) / Code: A860 / 坪山"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA961",
  "subinvDescription": "BYDA (电控工厂) / Code: A961 / 坪山"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA963",
  "subinvDescription": "BYDA (电源工厂) / Code: A963 / 坪山"
 },
 {
  "orgId": 7,
  "secondaryInventoryName": "SZBYDA964",
  "subinvDescription": "BYDA (电喷工厂) / Code: A964 / 坪山"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "OSWF",
  "subinvDescription": "Stock Written Off"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store 1 in Thailand w/o Locator"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "THNE1",
  "subinvDescription": "经MCE Office？购，最终Physical Subinventory"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "THTH2",
  "subinvDescription": "Store 2 in Thailand w/o Locator"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "THHK2",
  "subinvDescription": "Store 2 in Hongkong w/o Locator"
 },
 {
  "orgId": 220,
  "secondaryInventoryName": "THTH1",
  "subinvDescription": "Store 1 in Thailand w/o Locator"
 },
 {
  "orgId": 100,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 100,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store1 for MCO Extenral Office"
 },
 {
  "orgId": 82,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store1 for MCO Internal Office"
 },
 {
  "orgId": 82,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 },
 {
  "orgId": 21,
  "secondaryInventoryName": "STORE1",
  "subinvDescription": "Store 1 in Hong Kong w/o Locator"
 },
 {
  "orgId": 21,
  "secondaryInventoryName": "STAGING",
  "subinvDescription": "Staging"
 }
];
